#ifndef _SS3D_SERVICE_KEY_H_
#define _SS3D_SERVICE_KEY_H_

#define SUPER_THRONE_SVR_ID  (100)  // 超级王座服务器id,全game只有一个服
#define SUPER_THRONE_SVR_ID_BEGIN  (100)  
#define SUPER_THRONE_SVR_ID_END  (100)  
#define AVA_BATTLE_SVR_BEGIN (10000)//ava battle svr begin id
#define AVA_BATTLE_SVR_END (20000)

#define AL_LEGION_BATTLE_SVR_BEGIN (30000)//al legion battle svr begin id
#define AL_LEGION_BATTLE_SVR_END (40000)

#define SHAMA_BATTLE_SVR_BEGIN (50000)//shama battle svr begin id
#define SHAMA_BATTLE_SVR_END (80000)

enum EProxySearchUserIDType
{
    EN_PROXY_USERID_TYPE__UIN = 0,
    EN_PROXY_USERID_TYPE__DID = 1,
    EN_PROXY_USERID_TYPE__UID = 2,
};

enum EClientReqMode
{
    EN_CLIENT_REQ_MODE__HTTP = 0,
    EN_CLIENT_REQ_MODE__TCP,
};

enum EClientUrlEncryptType
{
    EN_CLIENT_REQ_ENTYPE__NO = 0,
    EN_CLIENT_REQ_ENTYPE__YES,
};

enum EContentType
{
    EN_CONTENT_TYPE__STRING = 0,
    EN_CONTENT_TYPE__BJSON,
};

enum ENetTaskType
{
    EN_NET_TASK_TYPE__SESSION = 0,
    EN_NET_TASK_TYPE__DELAY_TASK,
    EN_NET_TASK_TYPE__LOGIC_CONTROL_TASK,
};

enum EEventRequestType
{
    EN_EVENT_REQUEST_GET_CUR_EVENT = 0,
    EN_EVENT_REQUEST_ADD_SCORE,
    EN_EVENT_REQUEST_GET_HISTORY,
    EN_EVENT_REQUEST_SHARE_SCORE,

    EN_EVENT_REQUEST_BATCH_ADD_SCORE = 7,
    EN_EVENT_REQUEST_COLLECT_EVENT_REWARD = 8,

    EN_EVENT_REQUEST_RECEIVE_AL_EVENT_TASK = 10,
    EN_EVENT_REQUEST_COLLECT_AL_EVENT_TASK_REWARD = 11,

    EN_EVENT_REQUEST_ADD_THEME_SCORE_BATCH = 12,

    EN_EVENT_REQUEST_BATTLE_PASS_UNLOCK = 13,
    EN_EVENT_REQUEST_BATTLE_PASS_CLAIM_REWARD = 14,


    EN_EVENT_REQUEST_CITY_SKIN_STAR_UP_GET_RESULT = 19,

    EN_EVENT_REQUEST_KVK_SHARE_SCORE = 20,
    EN_EVENT_REQUEST_KVK_GET_WAR_STATION = 23,


    EN_EVENT_REQUEST_BANDIT_ALLIANCE_BALANCE = 30,
    EN_EVENT_REQUEST_BANDIT_USER_INFO_UPDATE = 31,
    /*
    //EN_EVENT_REQUEST_GET_CUR_EVENT = 0, // 已废弃
    EN_EVENT_REQUEST_ADD_SCORE = 1,
    EN_EVENT_REQUEST_GET_ALL_EVENT_BASIC,
    EN_EVENT_REQUEST_GET_EVENT_INFO,
    EN_EVENT_REQUEST_BATCH_ADD_SCORE,
    EN_EVENT_REQUEST_SHARE_SCORE,
    EN_EVENT_REQUEST_GET_HISTORY,
    EN_EVENT_REQUEST_RECEIVE_AL_EVENT_TASK,
    EN_EVENT_REQUEST_COLLECT_AL_EVENT_TASK_REWARD,
    */
};

enum EPVPRequestType
{
    EN_PVP_REQUEST_UPDATE_INFO = 0,
    EN_PVP_REQUEST_CHANGE_SCORE = 1,
    EN_PVP_REQUEST_MATCH_PLAYER = 2,
    EN_PVP_REQUEST_GET_PVP_INFO = 3,
    EN_PVP_REQUEST_REMOVE_INFO = 4,
};
enum EDownNodeType
{
    DOWN_NODE_TYPE__BEGIN = 0,

    DOWN_NODE_TYPE__LOCK_SVR = 2,
    DOWN_NODE_TYPE__AWS_PROXY = 3,

    DOWN_NODE_TYPE__DATA_SERVICE = 4,

    DOWN_NODE_TYPE__DS_ALLIANCE = 5,
    DOWN_NODE_TYPE__DS_KINGDOM  = 6,
    DOWN_NODE_TYPE__DS_PLAYER = 7,
    DOWN_NODE_TYPE__DS_PROXY = 8,
    DOWN_NODE_TYPE__LOGIC_CONTROL = 9,
    DOWN_NODE_TYPE__ACTION_TRIIGER = 11,
    DOWN_NODE_TYPE__DS_COMPUTE = 12,
    DOWN_NODE_TYPE__GAME_SERVER = 15,
    DOWN_NODE_TYPE__DS_AL_GIFT = 16,
    DOWN_NODE_TYPE__RAID_SERVER = 18,
    DOWN_NODE_TYPE__DS_GLOBAL_SVR = 57,            //全局注册
    
    DOWN_NODE_TYPE__EVENT_PROXY = 10,           //proxy全局注册，独立服务集群
    DOWN_NODE_TYPE__DATA_CENTER_PROXY = 13,     //全局注册
    DOWN_NODE_TYPE__EVENT_CENTER = 14,          //proxy全局注册，独立服务集群
    DOWN_NODE_TYPE__MAP_SVR_CENTER = 17,        //全局注册，logic进行路由，跨服
    DOWN_NODE_TYPE__AVA_BATTLE_SERVER = 17,     //全局注册，logic进行路由，跨服
    DOWN_NODE_TYPE__LEGION_BATTLE_SERVER = 19,  // 军团战战场服务，ds_compute进行路由，跨服
    DOWN_NODE_TYPE__GHOST_SERVER   = 20,  // 军团战战场服务，ds_compute进行路由，跨服

    DOWN_NODE_TYPE__UID_ACTION_SVR = 22, //全局注册,suid路由,跨服
    DOWN_NODE_TYPE__AID_ACTION_SVR = 23, //全局注册,aid路由
    DOWN_NODE_TYPE__BID_ACTION_SVR = 24, //全局注册,bid路由

    DOWN_NODE_TYPE__HU = 25,                    //逻辑集群注册
    DOWN_NODE_TYPE__REPORT_USER_SVR = 26,       //proxy全局注册，独立服务集群
    DOWN_NODE_TYPE__USM = 27,                   //全局注册

    DOWN_NODE_TYPE__RANK_SVR = 28,              //全局注册
    DOWN_NODE_TYPE__CHAT_SVR = 29,              //全局注册（kingdom、alliance拆开服务）
    DOWN_NODE_TYPE__HU_OP = 30,                 //不用注册
    DOWN_NODE_TYPE__PURCHAES_CHECK = 31,        //全局注册
    DOWN_NODE_TYPE__MAIL_USER_SVR = 32,         //proxy全局注册，独立服务集群
    DOWN_NODE_TYPE__LOGIN_SVR = 33,             //discard

    DOWN_NODE_TYPE__REDIS_PROXY_EVENT = 34,             //discard

    DOWN_NODE_TYPE__LOGIN_CENTER = 40,          //独立服务集群
    DOWN_NODE_TYPE__AU_MARCH = 41,              //不用注册
    DOWN_NODE_TYPE__USER_MGR = 42,              //discard

    DOWN_NODE_TYPE__IAP_SVR = 43,               //proxy全局注册，独立服务集群

    DOWN_NODE_TYPE__NOTIC_PUSH_SVR = 44,        //全局注册_待用

    DOWN_NODE_TYPE__THEME_EVENT_PROXY = 45,     //proxy全局注册，独立服务集群
    DOWN_NODE_TYPE__OP_SVR = 46,                //逻辑集群注册, chat\rank归类到这边
    DOWN_NODE_TYPE__AL_THEME_EVENT_PROXY = 47,  //proxy全局注册，独立服务集群

    DOWN_NODE_TYPE__TRANSLATE_PUBLIC = 48,       //全局注册
    DOWN_NODE_TYPE__TRANSLATE_BASE = 49,        //proxy全局注册，独立服务集群
    DOWN_NODE_TYPE__USER_LINKER = 50,           //全局注册，sid路由
    //------------------------------------------------------

    DOWN_NODE_TYPE__EVENT_RANKSERVER = 51,      //discard
    DOWN_NODE_TYPE__IAP_PROXY = 52,
    DOWN_NODE_TYPE__EVENT_PROXY_FOR_THEME = 54,
    DOWN_NODE_TYPE__DATA_PROXY = 55,            //discard
    DOWN_NODE_TYPE__USER_SVR = 56,              //全局注册
    DOWN_NODE_TYPE__GLOBAL_SVR = 57,            //全局注册
    DOWN_NODE_TYPE__ALLIANCE_SVR = 58,          //全局注册
    DOWN_NODE_TYPE__KINGDOM_SVR = 59,           //全局注册
    DOWN_NODE_TYPE__REDIS_PROXY = 60,           //数据服务内独立集群
    DOWN_NODE_TYPE__MSG_SVR = 61,                 //全局注册

    DOWN_NODE_TYPE__UNKNOWN_SVR_0 = 62,
    DOWN_NODE_TYPE__REPORT_ABS = 63,
    DOWN_NODE_TYPE__MAIL_ABS = 64,

    DOWN_NODE_TYPE__DELAY_MSG_SVR = 65,

    DOWN_NODE_TYPE__RANK_PLAYER = 69,              //全局注册

    DOWN_NODE_TYPE__NOTI_SVR = 71,

    DOWN_NODE_TYPE__PVP_SVR = 204,
    DOWN_NODE_TYPE__NEW_EVENT_PROXY = 74,

    DOWN_NODE_TYPE__ABS_SVR = 79,

    DOWN_NODE_TYPE__OP_REDIS_PROXY = 80,
    DOWN_NODE_TYPE__EVENT_CENTER_NEW = 81,

    DOWN_NODE_TYPE__BATTLE_PASS_EVENT = 82,
    DOWN_NODE_TYPE__OP_SVR_HTTP = 83,

    DOWN_NODE_TYPE__AVA_BATTLE_CACHE = 84,
    DOWN_NODE_TYPE__AVA_BATTLE_PROXY = 85,
    DOWN_NODE_TYPE__AVA_BATTLE_EVENT = 86,
    
    DOWN_NODE_TYPE__MAP_THUMBNAIL_SVR = 87,

    DOWN_NODE_TYPE__BANDIT_EVENT = 88, //土匪来袭活动
    DOWN_NODE_TYPE__AL_LEGION_EVENT = 89, //军团战活动
    
    DOWN_NODE_TYPE__IAP_SVR_NEW = 90,         
    
    DOWN_NODE_TYPE__EVENT_PROXY_SVR = 91,

    DOWN_NODE_TYPE__EVENT_PROXY_NEW = 1060,

    DOWN_NODE_TYPE__AUCTION_SVR = 93,

    DOWN_NODE_TYPE__CHAT_CHANNEL = 95,
    DOWN_NODE_TYPE__CHAT_INDEX = 96,
    

    DOWN_NODE_TYPE__ACCOUNT_SVR = 100,

    DOWN_NODE_TYPE__ACCOUNT_USER_SVR = 101,
    DOWN_NODE_TYPE__ACCOUNT_PRODUCT_SVR = 102,
    DOWN_NODE_TYPE__RPG_BATTLE_SVR = 103,
    DOWN_NODE_TYPE__RPG_BATTLE_HISTORY = 104,
    DOWN_NODE_TYPE__RPG_BATTLE_PROXY = 105,

    DOWN_NODE_TYPE__REDIS_PROXY_SENTINEL = 120,  // redis_proxy_sentinel
    DOWN_NODE_TYPE__BATTLE_SERVER = 121,

    DOWN_NODE_TYPE__EVENT_SVR_BEGIN = 200,      // 活动服注册节点区间, 任意活动可注册该区间的任意节点, 但不能冲突且要通知运营修改排期配置的node_type

    DOWN_NODE_TYPE__DEMON_EXORCIST_EVENT_SVR = 219,

    DOWN_NODE_TYPE__USER_EVENT = 224,
    DOWN_NODE_TYPE__RANK_EVENT_SVR = 225,
    DOWN_NODE_TYPE__LVL_BATTLE_SERVER = 229,     //全局注册，logic进行路由，跨服
    DOWN_NODE_TYPE__EVENT_SVR_END = 299,

    DOWN_NODE_TYPE__MAIL_INDEX = 300,

    DOWN_NODE_TYPE__MAIL_PROXY = 310,

    DOWN_NODE_TYPE__BATTLE_REPORT_SVR = 316,

    DOWN_NODE_TYPE__REPORT_INDEX_UID = 400,
    DOWN_NODE_TYPE__REPORT_INDEX_AID = 401,
    DOWN_NODE_TYPE__REPORT_PROXY = 410,

    DOWN_NODE_TYPE__TIME_SVR = 411,
    DOWN_NODE_TYPE__GAME_MAP_CACHE = 412,
    DOWN_NODE_TYPE__CLIENT_POLLING_SVR = 420, // client_polling_svr
	
	DOWN_NODE_TYPE__PROHIBIT_PROXY = 500,
    DOWN_NODE_TYPE__IMAGE_PROXY = 501,

    DOWN_NODE_TYPE__ACTION_TRIGGER_SVR = 600,

    DOWN_NODE_TYPE__AL_RECORD_SVR = 601,
    DOWN_NODE_TYPE__AL_AUTO_MSG_SVR = 602,

    DOWN_NODE_TYPE__COMMON_RECORD_SVR = 603,

    DOWN_NODE_TYPE__USER_IMPORT_SVR = 604,

    DOWN_NODE_TYPE__SUPER_WANG_EVENT_PROXY = 999,
    
    DOWN_NODE_WORNG_NODE_INFO = 999
};

enum EServiceType
{
    //--------------------------------------new----------------------
    // hu <---> lock
    EN_HU2LOCK__BEGIN = 4000,
    EN_SERVICE_TYPE_LOCK__GET_REQ,
    EN_SERVICE_TYPE_LOCK__RELEASE_REQ,

    EN_LOCK2HU__BEGIN = 4100,
    EN_SERVICE_TYPE_LOCK__GET_RSP,
    EN_SERVICE_TYPE_LOCK__RELEASE_RSP,

    EN_SERVICE_TYPE__DATA_SERVICE = 10000,
    EN_SERVICE_TYPE__DS_ALLIANCE = 10001,
    EN_SERVICE_TYPE__DS_KINGDOM = 10002,
    EN_SERVICE_TYPE__DS_PLAYER = 10003,
    EN_SERVICE_TYPE__DS_COMPUTE = 10004,

    //action_svr
    EN_SERVICE_TYPE__ACTION_SVR = 30000,

    // redis proxy
    EN_SERVICE_TYPE__REDIS_PROXY__READ = 32000,
    EN_SERVICE_TYPE__REDIS_PROXY__WRITE = 32001,
    EN_SERVICE_TYPE__REDIS_PROXY__DEBUG = 32002,
    EN_SERVICE_TYPE__REDIS_PROXY__SENTINEL = 32003, // redis_proxy给redis_sentinel发的请求
    EN_SERVICE_TYPE__REDIS_PROXY__FLUSHALL = 32004,

    //redis proxy refresh
    EN_REDIS_PROXY_KEY__REGET_FLAG = 20005,
    EN_REDIS_PROXY_KEY__REGET_REQ = 20006,

    //--------------------------------------------------------------------
    //--------------------------------------old---------------------------
    //--------------------------------------------------------------------
    //注册部分保留1000开始的key值///////

    // CLIENT层
    EN_SERVICE_TYPE__CLIENT__BEGIN = 2000,
    EN_SERVICE_TYPE__CLIENT__HEARTBEAT_REQ,  // heart beat
    EN_SERVICE_TYPE__CLIENT__HEARTBEAT_RSP,
    EN_SERVICE_TYPE__CLIENT__COMMAND_REQ,    // command
    EN_SERVICE_TYPE__CLIENT__COMMAND_RSP,
    EN_SERVICE_TYPE__CLIENT__LOGIN_REQ,      // 登录请求
    EN_SERVICE_TYPE__CLIENT__LOGIN_RSP,
    EN_SERVICE_TYPE__CLIENT__DATA_PUSH_REQ,  // data push
    EN_SERVICE_TYPE__CLIENT__DATA_PUSH_RSP,
    EN_SERVICE_TYPE__CLIENT__CREATE_NEW_PLAYER_REQ, // new player create //废弃, 没有地方在用...
    EN_SERVICE_TYPE__CLIENT__CHAT_REQ, //chat
    EN_SERVICE_TYPE__CLIENT__CHAT_RSP,
    EN_SERVICE_TYPE__CLIENT__RANK_REQ, //rank
    EN_SERVICE_TYPE__CLIENT__RANK_RSP,
    EN_SERVICE_TYPE__CLIENT__INC_REFRESH_RSP,
    EN_SERVICE_TYPE__CLIENT__ALL_REFRESH_RSP,

    EN_SERVICE_TYPE__SVR__SPECIAL = 2018,

    EN_SERVICE_TYPE__CLIENT__OP_SVR_REQ = 2019,
    EN_SERVICE_TYPE__CLIENT__OP_SVR_RSP = 2020,

    EN_SERVICE_TYPE__CLIENT__CHAT_INDEX_MGR_REQ = 2021,
    EN_SERVICE_TYPE__CLIENT__CHAT_INDEX_MGR_RSP = 2022,
    EN_SERVICE_TYPE__CLIENT__INC_REFRESH_GROUP_LIST_RSP = 2023,
    EN_SERVICE_TYPE__CLIENT__INC_REFRESH_FRIEND_LIST_RSP = 2024,
    EN_SERVICE_TYPE__CLIENT__INC_REFRESH_INVITE_LIST_RSP = 2025,
    EN_SERVICE_TYPE_CHAT_CHANNEL_REQ = 2030,
    EN_SERVICE_TYPE_CHAT_CHANNEL_RSP = 2031,

    // LINKER层
    EN_SERVICE_TYPE__LINKER__BEGIN = 2100,
    EN_SERVICE_TYPE__LINKER__PLAYER_MGR_REQ, // player online status mgr //废弃, 没有地方在用...
    EN_SERVICE_TYPE__LINKER__PLAYER_MGR_RSP,

    //LOGIC层
    EN_SERVICE_TYPE__LOGIC__BEGIN = 2200,

    // DATA层
    EN_SERVICE_TYPE__DATA__BEGIN = 2300,
    EN_SERVICE_TYPE__DATA__NORMAL_REQ,
    EN_SERVICE_TYPE__DATA__NORMAL_RSP,
    EN_SERVICE_TYPE__DATA__MAP_REQ,
    EN_SERVICE_TYPE__DATA__MAP_RSP,
    EN_SERVICE_TYPE__DATA__REPORT_REQ,
    EN_SERVICE_TYPE__DATA__REPORT_RSP,
    EN_SERVICE_TYPE__DATA__MAIL_REQ,
    EN_SERVICE_TYPE__DATA__MAIL_RSP,
    EN_SERVICE_TYPE__DATA__ACTION_REQ,
    EN_SERVICE_TYPE__DATA__ACTION_RSP,
    EN_SERVICE_TYPE__DATA__TEMP_REQ,
    EN_SERVICE_TYPE__DATA__TEMP_RSP,
    EN_SERVICE_TYPE__DATA__EVENT_REQ,
    EN_SERVICE_TYPE__DATA__EVENT_RSP,
    EN_SERVICE_TYPE__DATA__RANK_REQ,
    EN_SERVICE_TYPE__DATA__RANK_RSP,
    EN_SERVICE_TYPE__DATA__ACCOUNT_REQ,
    EN_SERVICE_TYPE__DATA__ACCOUNT_RSP,


    // hu <---> hs
    EN_HU2HS__BEGIN = 3000,
    EN_SERVICE_TYPE_HU2HS__SEARCH_REQ,
    EN_SERVICE_TYPE_HU2HS__UPDT_REQ,
    EN_SERVICE_TYPE_QUERY_DYNAMODB_REQ, //leyton add 2013-08-20
    EN_SERVICE_TYPE_QUERY_MYSQL_REQ, //leyton add 2013-10-15

    EN_HS2HU__BEGIN = 3100,
    EN_SERVICE_TYPE_HS2HU__SEARCH_RSP,
    EN_SERVICE_TYPE_HS2HU__UPDT_RSP,
    EN_SERVICE_TYPE_QUERY_DYNAMODB_RSP, //leyton add 2013-08-20
    EN_SERVICE_TYPE_QUERY_MYSQL_RSP, //leyton add 2013-10-15

    // hu <---> lock
    //EN_HU2LOCK__BEGIN = 4000,
    //EN_SERVICE_TYPE_HU2LOCK__GET_REQ,
    //EN_SERVICE_TYPE_HU2LOCK__RELEASE_REQ,

    //EN_LOCK2HU__BEGIN = 4100,
    //EN_SERVICE_TYPE_LOCK2HU__GET_RSP,
    //EN_SERVICE_TYPE_LOCK2HU__RELEASE_RSP,

    // hu <---> chat_svr
    EN_HU2CHAT__BEGIN = 5000,
    EN_HU2CHAT__SEARCH_REQ,
    EN_HU2CHAT__UPDT_REQ,

    EN_CHAT2HU__BEGIN = 5100,
    EN_CHAT2HU__SEARCH_RSP,
    EN_CHAT2HU__UPDT_RSP,

    //hu <---> auction_svr     nemo
    EN_HU2AUCTION__BEGIN = 6000,
    EN_HU2AUCTION__PB_REQ,

    EN_AUCTION2HU__BEGIN = 6100,
    EN_AUCTION2HU__PB_RSP,


    EN_SERVICE_TYPE_QUERY_EVENT_REQ = 7000,
    EN_SERVICE_TYPE_QUERY_EVENT_RSP,

    // cache
    EN_SERVICE_TYPE_CACHE_REQ = 8000,
    EN_SERVICE_TYPE_CACHE_RSP,

    // translate
    EN_SERVICE_TYPE_TRANSLATE_REQ = 9000,
    EN_SERVICE_TYPE_TRANSLATE_RSP,

    // data center
    EN_SERVICE_TYPE_DATA_CENTER_REQ = 10000,  //请求包的service_type
    EN_SERVICE_TYPE_DATA_CENTER_RSP = 10001,  //返回包的service_type

    // IU
    EN_SERVICE_TYPE__IU_REQUEST = 11000,
    EN_SERVICE_TYPE__IU_RESPONSE = 11001,

    //map_svr
    EN_SERVICE_TYPE_MAP_SVR_PROXY_REQ = 20000,
    EN_SERVICE_TYPE_MAP_SVR_PROXY_RSP = 20001,

    EN_SERVICE_TYPE_MAP_SVR_CENTER_REQ = 20010,
    EN_SERVICE_TYPE_MAP_SVR_CENTER_RSP = 20011,

    EN_SERVICE_TYPE_ACTION_PROXY_REQ = 20020,
    EN_SERVICE_TYPE_ACTION_PROXY_RSP = 20021,

    EN_SERVICE_TYPE_ACTION_CENTER_REQ = 20030,
    EN_SERVICE_TYPE_ACTION_CENTER_RSP = 20031,

    EN_SERVICE_TYPE_REPORT_PROXY_REQ = 20050,
    EN_SERVICE_TYPE_REPORT_PROXY_RSP = 20051,

    EN_SERVICE_TYPE_REPORT_INDEX_REQ = 20056,
    EN_SERVICE_TYPE_REPORT_INDEX_RSP = 20057,

    EN_SERVICE_TYPE_PURCHASE_CHECK_REQ = 20060,
    EN_SERVICE_TYPE_PURCHASE_CHECK_RSP = 20061,

    EN_SERVICE_TYPE_MAIL_PROXY_REQ = 20070,
    EN_SERVICE_TYPE_MAIL_PROXY_RSP = 20071,

    EN_SERVICE_TYPE_MAIL_INDEX_REQ = 20076,
    EN_SERVICE_TYPE_MAIL_INDEX_RSP = 20077,

    EN_SERVICE_TYPE_USR_SVR_REQ = 20090,
    EN_SERVICE_TYPE_USR_SVR_RSP = 20091,

    EN_SERVICE_TYPE_GLOBAL_SVR_REQ = 20100,
    EN_SERVICE_TYPE_GLOBAL_SVR_RSP = 20101,

    EN_SERVICE_TYPE_ALLIANCE_SVR_REQ = 20110,
    EN_SERVICE_TYPE_ALLIANCE_SVR_RSP = 20111,

    EN_SERVICE_TYPE_KINGDOM_SVR_REQ = 20120,
    EN_SERVICE_TYPE_KINGDOM_SVR_RSP = 20121,

    EN_SERVICE_TYPE_MAP_SVR_REQ = 20010,
    EN_SERVICE_TYPE_MAP_SVR_RSP = 20011,

    EN_SERVICE_TYPE_REPORT_ABS_GET_REQ = 20200,
    EN_SERVICE_TYPE_REPORT_ABS_PUT_REQ = 20201,
    EN_SERVICE_TYPE_REPORT_ABS_RSP = 20202,

    EN_SERVICE_TYPE_MAIL_ABS_GET_REQ = 20210,
    EN_SERVICE_TYPE_MAIL_ABS_PUT_REQ = 20211,
    EN_SERVICE_TYPE_MAIL_ABS_RSP = 20212,

    EN_SERVICE_TYPE_EVENT_CENTER_REQ = 20220,
    EN_SERVICE_TYPE_EVENT_CENTER_RSP = 20221,

    EN_SERVICE_TYPE_EVENT_PROXY_REQ = 20230,
    EN_SERVICE_TYPE_EVENT_PROXY_RSP = 20231,

    //user_linker-->user_mgr
    EN_SERVICE_TYPE_UL2UM_DATA_SYNC_REQ = 30001,

    EN_SERVICE_TYPE_DATA_PROXY_REQ = 31000,
    EN_SERVICE_TYPE_DATA_PROXY_RSP,

    // redis proxy
    //EN_SERVICE_TYPE__REDIS_PROXY__READ = 32000,
    //EN_SERVICE_TYPE__REDIS_PROXY__WRITE = 32001,
    //EN_SERVICE_TYPE__REDIS_PROXY__DEBUG = 32002,

    EN_SERVICE_TYPE_MSG_SRV_REQ = 33000,
    EN_SERVICE_TYPE_MSG_SRV_RSP = 33001,

    EN_SERVICE_TYPE__DATA__RANK_URL_REQ = 34038,
    EN_SERVICE_TYPE__DATA__RANK_JSON_REQ = 34039,
    EN_SERVICE_TYPE__DATA__RANK_RSP_NEW = 34040,

    EN_SERVICE_TYPE__ACCOUNT_SVR_REQ = 34079,
    EN_SERVICE_TYPE__ACCOUNT_SVR_RSP = 34080,

    EN_SERVICE_TYPE_DELAY_MSG_REQ = 35000,
    EN_SERVICE_TYPE_DELAY_MSG_PUSH = 35001,
    EN_SERVICE_TYPE_DELAY_MSG_RSP = 35002,

    EN_SERVICE_TYPE__AVA_EVENT_REQ = 36000,
    EN_SERVICE_TYPE__AVA_EVENT_RSP = 36001,

    EN_SERVICE_TYPE__AVA_BATTLE_CACHE_REQ = 36010,
    EN_SERVICE_TYPE__AVA_BATTLE_CACHE_RSP = 36011,
    
    EN_SERVICE_TYPE__AVA_BATTLE_PROXY_REQ = 36020,
    EN_SERVICE_TYPE__AVA_BATTLE_PROXY_RSP = 36021,

    EN_SERVICE_TYPE__MAP_THUMBNAIL_SVR_REQ = 36030,
    EN_SERVICE_TYPE__MAP_THUMBNAIL_SVR_RSP = 36040,

    EN_SERVICE_TYPE__AL_LEGION_EVENT_REQ = 36050,
    EN_SERVICE_TYPE__AL_LEGION_EVENT_RSP = 36051,

    EN_SERVICE_TYPE__AUCTION_SVR_REQ = 36060,
    EN_SERVICE_TYPE__AUCTION_SVR_RSP = 36061,

    EN_SERVICE_TYPE__ABS_SVR_GET_REQ = 36070,
    EN_SERVICE_TYPE__ABS_SVR_PUT_REQ = 36071,

    EN_SERVICE_TYPE__CLIENT__PUSH_HEARTBEAT_REQ = 36080,  // push heart beat
    EN_SERVICE_TYPE__CLIENT__PUSH_HEARTBEAT_RSP = 36081,

    EN_SERVICE_TYPE__CLIENT_PB_REQ = 36090, // client_polling_svr给到的service_type
    EN_SERVICE_TYPE__CLIENT_PB_RSP = 36091,
};

enum EServiceKey
{
    //////////////////////////
    // GLOBAL KEY
    EN_GLOBAL_KEY__BEGIN = 0,
    EN_GLOBAL_KEY__RES_CODE,
    EN_GLOBAL_KEY__RES_COST_TIME,
    EN_GLOBAL_KEY__RES_TOTAL_RES_NUM,
    EN_GLOBAL_KEY__RES_CUR_RES_NUM,
    EN_GLOBAL_KEY__RES_BUF,
    EN_GLOBAL_KEY__REQ_SEQ,
    EN_GLOBAL_KEY__RES_BUF_COMPRESS_FLAG,

    //----dynamodb使用----
    EN_GLOBAL_KEY__INDEX_NO,
    EN_GLOBAL_KEY__TABLE_NAME,
    EN_GLOBAL_KEY__OPERATOR_NAME,
    EN_GLOBAL_KEY__DB_IDX,
    EN_GLOBAL_KEY__AWSTBL_CACHE_MODE,
    EN_GLOBAL_KEY__AWSTBL_ROUTE_FLD,
    EN_GLOBAL_KEY__AWSTBL_ROUTE_THRD,
    EN_GLOBAL_KEY__AWSTBL_HASH_KEY,
    EN_GOLBAL_KEY__AWSTBL_RANGE_KEY,

    //
    EN_GLOBAL_KEY__REQ_BUF = 16,
    EN_GLOBAL_KEY__REQ_TYPE = 17,   // 0: string 1: bjson 2: pb
    EN_GLOBAL_KEY__RES_TYPE = 18,
    EN_GLOBAL_KEY__RES_CAN_RETRY = 19,   //用于dynamodb通知ds，在ret_code发生错误时，是否应该重试

    //
    EN_GLOBAL_KEY__REQ_NEED_RESPONSE = 20, //表明上游是否需要回包
    EN_GLOBAL_KEY__CLIENT_RES_TYPE, //返包给客户端的类型
    EN_GLOBAL_KEY__CLIENT_RES_SEQ, //作为主包返给客户端时需要携带的seq
    EN_GLOBAL_KEY__GLOBAL_SEQ,
    EN_GLOBAL_KEY__REQ_CMD,
    EN_GLOBAL_KEY__RES_CMD,
    EN_GLOBAL_KEY__REQ_NEED_RSP_CONTENT,
    EN_GLOBAL_KEY__REQ_DATA_KEY,
    EN_GLOBAL_KEY__REQ_DATA_SERVICE,
    EN_GLOBAL_KEY__RES_DATA_SERVICE,
    EN_GLOBAL_KEY__REQ_KEY_NUM,
    EN_GLOBAL_KEY__REQ_KEY_LIST,
    EN_GLOBAL_KEY__REQ_TIMEOUT_US,
    EN_GLOBAL_KEY__CLIENT_IP,
    EN_GLOBAL_KEY__DEBUG_RESULT,        //wave@20200701: for redis debug rsp
    EN_GLOBAL_KEY__SERVICE_REQ_TYPE,    // 代替原来老svr的service_type
    EN_GLOBAL_KEY__SERVICE_RES_TYPE,    // 代替原来老svr的service_type

    //--------------------------------------------------------------------------------//
    
    //新加key....
    //请求相关
    EN_GLOBAL_KEY__REQUEST_TYPE,
    EN_GLOBAL_KEY__EXTRA_INFO,
    EN_GLOBAL_KEY__NEXT_CMD,
    EN_GLOBAL_KEY__NEXT_DATA_KEY,
    EN_GLOBAL_KEY__NEXT_DATA_SERVICE,
    EN_GLOBAL_KEY__RAW_REQUEST_INFO,

    //推送相关
    EN_GLOBAL_KEY__TARGET_TYPE,
    EN_GLOBAL_KEY__TARGET_LIST_SIZE, //废弃
    EN_GLOBAL_KEY__TARGET_LIST,
    EN_GLOBAL_KEY__EXCEPT_LIST_SIZE, //废弃
    EN_GLOBAL_KEY__EXCEPT_TYPE,
    EN_GLOBAL_KEY__EXCEPT_LIST,
    EN_GLOBAL_KEY__TARGET_KEY,
    EN_GLOBAL_KEY__USER_LIST_SIZE,
    EN_GLOBAL_KEY__USER_LIST,

    //返包相关
    EN_GLOBAL_KEY__RES_FINISH,
    EN_GLOBAL_KEY__RES_NEXT_CMD,

    // account 返包
    EN_GLOBAL_KEY__TARGET_UID,
    EN_GLOBAL_KEY__TARGET_AID,
    EN_GLOBAL_KEY__TARGET_SID,

    // tanslate
    EN_GLOBAL_KEY__LANG_FROM,
    EN_GLOBAL_KEY__LANG_TO,
    EN_GLOBAL_KEY__OPERATE,
    EN_GLOBAL_KEY__DB_NAME,
    EN_GLOBAL_KEY__DB_KEY,
    EN_GLOBAL_KEY__REGET_FLAG,
    EN_GLOBAL_KEY__REGET,
    EN_GLOBAL_KEY__IDS,
    EN_GLOBAL_KEY__NEED_DELAY,

    EN_GLOBAL_KEY__NEED_LOCK,
    EN_GLOBAL_KEY__NEED_UNLOCK,
    //--------------------------------------------------------------------------------//

    EN_GLOBAL_KEY__PAGE_FUNCTION_KEY, //废弃
    EN_GLOBAL_KEY__NEED_CLIENT_RES,
    EN_GLOBAL_KEY__CLIENT_RES_BUF,

    EN_GLOBAL_KEY__RES_NEW_PLAYER_UID,
    EN_GLOBAL_KEY__REQ_IS_ARRAY,

    EN_GLOBAL_KEY__RES_ERR_MSG,
    EN_GLOBAL_KEY__MSG_TYPE,

    EN_GLOBAL_KEY__CLIENT_REQUESTOR_UID,
    EN_GLOBAL_KEY__PACKET_FROM,
    
    EN_GLOBAL_KEY__UL_CONN_ACCEPT_TIME,
    EN_GLOBAL_KEY__CLIENT_REQ_HIGH_CMD, // 高优先级命令

    EN_GLOBAL_KEY__RES_STRING,

    // hu <-> hs
    EN_KEY_HU2HS__BEGIN = 5000,
    EN_KEY_HU2HS__REQ_NUM,
    EN_KEY_HU2HS__REQ_BUF,

    // hu -> lock
    EN_LOCK_KEY__BEGIN = 6000,
    EN_LOCK_KEY__REQ_KEY_NUM,
    EN_LOCK_KEY__REQ_KEY_LIST,
    EN_LOCK_KEY__REQ_TIMEOUT_US,

    // translate
    EN_TRANSLATE__BEGIN = 9000,
    EN_TRANSLATE__REQ_SEQ,
    EN_TRANSLATE__TYPE,
    EN_TRANSLATE__OPERATE,      // 翻译操作
    EN_TRANSLATE__RAW_LANG,     // 翻译的原语言
    EN_TRANSLATE__RESULT_LANG,  // 翻译后的语言
    EN_TRANSLATE__CONTENT,      // 翻译的请求内容
    EN_TRANSLATE__RESULT,       // 翻译的结果内容
    EN_TRANSLATE__RES_CODE,     // 翻译服务的返回码

    EN_REDIS_PROXY_KEY__DEBUG_MODE = 20002,
    EN_GLOBAL_KEY__CHAT_SCENE_KEY = 20014,

    EN_GLOBAL_KEY__LOGIC_CONTROL_PUSH_BUF = 20100,       // logic_control推包内容
    EN_GLOBAL_KEY__LOGIC_CONTROL_FORWARD_SID = 20101,    // game_server跨服移城的目标sid
    EN_GLOBAL_KEY__REQUEST_FROM = 20102,                 // 请求来源，参照 ERequestType

    EN_GLOBAL_KEY__USER_LINKER_ADDR,
    EN_GLOBAL_KEY__USER_LOGIN_TIME,
    EN_GLOBAL_KEY__UP_SERVER_KEY,
    EN_GLOBAL_KEY__UP_SERVER_REQUEST_SEQ,
    
    EN_GLOBAL_KEY__USER_LINKER_KEY = 20110,
    EN_GLOBAL_KEY__NEED_INC_PACKAGE = 20111,
    EN_GLOBAL_KEY__USER_LOGIN_DATA = 20112,
    EN_GLOBAL_KEY__REQUEST_FROM_NEW = 20113, // 参照 ERequestType
};

//给活动用的一些特殊key...
enum EHuRequestKey
{
    EN_HU_REQUEST_KEY__REQUEST_SEQ = 10001,
    EN_HU_REQUEST_KEY__REQUEST_TYPE = 10002,
    EN_HU_REQUEST_KEY__REQUEST_JSON = 10003,
    EN_HU_REQUEST_KEY__REQUEST_KSID = 10004,  // 数据类型TINT32
    EN_HU_REQUEST_KEY__REQUEST_UID = 10005,   // 数据类型TINT32
    EN_HU_REQUEST_KEY__REQUEST_AID = 10006,   // 数据类型TINT32

    EN_HU_REQUEST_KEY__REQUEST_SID = 10010, //后面废弃
    EN_HU_REQUEST_KEY__REQUEST_EVENT_TYPE = 10011, //后面废弃
    EN_HU_REQUEST_KEY__REQUEST_CMD = 11000, //后面废弃

    EN_HU_REQUEST_KEY__REQUEST_NEED_RESPONSE = 11001, // 默认会回包。数据类型TBOOL。TRUE表示需要回包，FALSE表示不需要回包

    //------------------------------ ava_battle 相关枚举 -------------------------------//
    // ava_battle_proxy
    EN_AVA_BATTLE_PROXY_REQ_PARAM_FIELD_BATTLE_ID = 30000,         // battle_id -- TINT64
    EN_AVA_BATTLE_PROXY_REQ_PARAM_FIELD_FORWARD_TYPE = 30001,      // 转发类型 直接传 down_type -- TINT32
    EN_AVA_BATTLE_PROXY_REQ_PARAM_FIELD_IS_RELIABLE = 30002,       // 是否可靠 传 0 表示不可靠，传 1 表示可靠 -- TINT32
    EN_AVA_BATTLE_PROXY_REQ_PARAM_FIELD_IS_KEY_DATA = 30003,       // 是否关键 传 0 表示关键，传 1 表示非关键 -- TINT32
    EN_AVA_BATTLE_PROXY_REQ_PARAM_FIELD_DATA = 30004,              // 转发数据 -- bytes
};

enum EHuRequestType
{
    EN_HU_REQUEST_TYPE__UNKNOWN = -1,
    EN_HU_REQUEST_TYPE__GET_IAP_PROMOTE = 0,
    EN_HU_REQUEST_TYPE__RECHARGE = 1,
    EN_HU_REQUEST_TYPE__DELAY_MSG = 2,
    EN_HU_REQUEST_TYPE__GET_SPECIAL_PROMOTE = 3,
    EN_HU_REQUEST_TYPE__GET_SUBSCRIPTION_REWARD = 4,
    EN_HU_REQUEST_TYPE__GET_SCENE_PROMOTE = 5,
    EN_HU_REQUEST_TYPE__GET_SHOP_PROMOTE = 6,
    EN_HU_REQUEST_TYPE__UNLOCK_EVIP = 7,
    EN_HU_REQUEST_TYPE__GET_EVIP_INFO = 8,
    EN_HU_REQUEST_TYPE__ADD_EVIP_POINT = 9,
    EN_HU_REQUEST_TYPE__GET_SPECIAL_IAP_PROMOTE_BY_SCENE_LIST = 10,

    EN_HU_REQUEST_TYPE__END
};

enum EPushDataType
{
    EN_PUSH_DATA_TYPE__UID = 1,
    EN_PUSH_DATA_TYPE__SID = 2,
    EN_PUSH_DATA_TYPE__AID = 3,
    EN_PUSH_DATA_TYPE__MAP = 4,
    EN_PUSH_DATA_TYPE__PAGE_FUNCTION = 5,
    EN_PUSH_DATA_TYPE__RAID = 6,
    EN_PUSH_DATA_TYPE__CHAT_SCENE = 7,
    EN_PUSH_DATA_TYPE__AVA = 8,
    EN_PUSH_DATA_TYPE__BATTLEFIELD = 9,
    EN_PUSH_DATA_TYPE__LVL = 10,
};

enum ERequestType
{
    EN_REQUEST_TYPE__UNKNOWN = 0,
    EN_REQUEST_TYPE__USER_LINKER,
    EN_REQUEST_TYPE__ACTION_TRIGGER,
    EN_REQUEST_TYPE__MSG_QUEUE,
    EN_REQUEST_TYPE__LOGIC_CONTROL,
    EN_REQUEST_TYPE__HTTP,
    EN_REQUEST_TYPE__LOGIN_CENTER,
    EN_REQUEST_TYPE__GAME_SERVER,
    EN_REQUEST_TYPE__CLIENT_POLLING_SVR,
    EN_REQUEST_TYPE__CLIENT,
    EN_REQUEST_TYPE__DS_PLAYER,
    EN_REQUEST_TYPE__ACTION_TRIGGER_SVR,
};

enum EClientResType
{
    EN_CLIENT_RES_TYPE__NONE = 0,
    EN_CLIENT_RES_TYPE__NORMAL,
    EN_CLIENT_RES_TYPE__RSP,
};

// 定义系统的结果码
enum ETshpErrCode
{
    EN_RET_CODE__SUCCESS = 0,
    EN_RET_CODE__ZERO,
    EN_RET_CODE__NO_ERROR, //不按套路出牌的错误码
    EN_RET_CODE__USER_DATA_IS_USING = 100,
    EN_RET_CODE__AWS_SUCCESS = 200,
    EN_RET_CODE__AWS_NULL = 201,
    EN_RET_CODE__UNEXPECTED = 1000,


    //client error
    EN_RET_CODE__NET_ERROR = 10000,
    EN_RET_CODE__TROOP_SLOT_LACK,       // 队列不够
    EN_RET_CODE__FORT_SLOT_LACK,        // 队列不够
    EN_RET_CODE__SCOUT_SLOT_LACK,       // 队列不够
    EN_RET_CODE__MARCH_SLOT_LACK,       // 队列不够
    EN_RET_CODE__TROOP_OVER_LOADED,     // march over thrd
    EN_RET_CODE__MARCH_COORD_INVALID,   //
    EN_RET_CODE__LAB_NOT_BUILDED,       //
    EN_RET_CODE__TEXT_INPUT_INVALID,    //
    EN_RET_CODE__TROOP_SIZE_ZERO,       //
    EN_RET_CODE__TO_RESTART_GAME,       //
    EN_RET_CODE__BOOK_MARK_EXIST,       //
    EN_RET_CODE__BOOK_MARK_OVERLOAD,    //

    EN_RET_CODE__NEED_TO_JOIN_ALLIANCE = 10166,
    EN_RET_CODE__CAPTURE_HERO = 10170,
    EN_RET_CODE__IS_RALLY_WAR_ATTACKED_BY_TARGET_ALLIANCE = 10174,
    EN_RET_CODE__ALREADY_HAS_TITLE = 10175,
    EN_RET_CODE__VIP_LEVEL_REACH_THE_TOP = 10177,
    EN_RET_CODE__DRAGON_EXP_REACH_THE_TOP = 10178,
    EN_RET_CODE__HERO_ENERGY_REACH_THE_TOP = 10179,
    EN_RET_CODE__HERO_IS_INVALID_TO_ADD_EXP = 10180,
    EN_RET_CODE__HERO_IS_INVALID_TO_ADD_ENERGY = 10181,

    EN_RET_CODE__CANNOT_CHANGE_SVR_IN_ALLIANCE = 10183,
    EN_RET_CODE__OVER_MAX_MARCH_DISTACE = 10185,
    EN_RET_CODE__TERMINATE_FRIENDLY_DIPLOMACY_FIRST = 10196,
    EN_RET_CODE__TERMINATE_HOSTILE_DIPLOMACY_FIRST = 10197,

    EN_RET_CODE__BLACKLIST_IS_FULL = 10199,

    EN_RET_CODE__CANNOT_MOVE_CITY_ON_RALLY_WAR = 10222,

    EN_RET_CODE__NEW_PROTECT_CANNOT_MOVE_TO_SPECAIL = 10232,
    EN_RET_CODE__USER_CANNOT_CLEAR,

    EN_RET_CODE__CANNOT_GIVE_SCORE = 10246,
    EN_RET_CODE__AL_MEMBER_NOT_PARTICIPATE = 10247,

    EN_RET_CODE__POINT_OVERNUMBERED = 10249,
    EN_RET_CODE__EVENT_ENDED = 10250,

    EN_RET_CODE_LORD_LV_REACH_THE_TOP = 10252,

    EN_RET_CODE__HAS_BEEN_MINING = 10254,

    EN_RET_CODE__CANNOT_REMOVE_DOUBLE_CRYSTAL = 10264,

    //EN_RET_CODE__SET_HIVE_COORD_INVALID = 10274,

    EN_RET_CODE__CHANGE_ALLIANCE_CANNOT_SHARE_SCORE = 10300, //自己换联盟, 不能送分
    EN_RET_CODE__CHANGE_ALLIANCE_CANNOT_RECIEVE_SCORE = 10301, //对方换联盟, 不能接受分

    EN_RET_CODE__FORTRESS_ALREADY_ASSIGNED_COMMANDER = 12052, // 要塞已经有指挥官了，不能派遣指挥官队列
    EN_RET_CODE__CANNOT_BEEN_COMMANDER_OF_FORTRESS = 12053, // 不是官员，无法成为要塞指挥官，不能派遣指挥官队列
    EN_RET_CODE__STRONGHOLD_ALREADY_ASSIGNED_COMMANDER = 12054, // 据点已经有指挥官了，不能派遣指挥官队列

    EN_RET_CODE__PRESENT_GIFT_HIGHER_FORCE = 10255, //只能向force小于自己的盟友送礼

    EN_RET_CODE__CITY_SKIN_STAR_UP_FAIL = 12058, // 升星失败
    EN_RET_CODE__SAME_SKIN_HAVE_PERMANENT_ACTIVE = 12059, // 同类皮肤已经被有永久激活
    EN_RET_CODE__CITY_SKIN_FUNCTION_NOT_UNLOCK = 12060, // 皮肤功能还未解锁，依赖于主城等级

    EN_RET_CODE__GOAL3 = 12074,

    EN_RET_CODE__PRESENT_GIFT_UNLOCK = 12075,   //未解锁送礼
    EN_RET_CODE__PRESENT_GIFT_MAX_NUM = 12076,  //超过送礼最大数

    EN_RET_CODE__RALLY_AL_POS_LIMIT = 100025,

    //server error
    EN_RET_CODE__TRANSPORT_COORD_INVALID = 20000,
    EN_RET_CODE__ATTACK_COORD_INVALID,
    EN_RET_CODE__REASSIGN_COORD_INVALID,
    EN_RET_CODE__REINFORCE_COORD_INVALID,
    EN_RET_CODE__MOVE_CITY_COORD_INVALID,
    EN_RET_CODE__KNIGHT_UNVAILABEL,
    EN_RET_CODE__PLAYER_NAME_EXIST,
    EN_RET_CODE__CITY_UNDER_PROTECT,
    EN_RET_CODE__RESOURCE_LACK,
    EN_RET_CODE__GEM_LACK,
    EN_RET_CODE__TROOP_LACK_USELESS,//useless
    EN_RET_CODE__MAIL_RECEIVER_INVALID,
    EN_RET_CODE__HAS_LOG_IN,
    EN_RET_CODE__POPULATION_NOT_ENOUGH,
    EN_RET_CODE__ITEM_NOT_ENOUGH,
    EN_RET_CODE__ALLIANCE_NAME_EXIST,
    EN_RET_CODE__YOURSELF_UNDER_PROTECT,
    EN_RET_CODE__GEM_SEQ_NO_INVALID,
    EN_RET_CODE__CAN_NOT_LEAVE_ALLIANCE,
    EN_RET_CODE__POPULATION_OVERLOAD,
    EN_RET_CODE__YOUR_ALLIANCE_MEMBER_OVER_LOAD,        // 联盟成员个数超限,批准加入时使用
    EN_RET_CODE__HAPPINESS_OVERLOAD,
    EN_RET_CODE__KNIGHT_EXP_OVERLOAD,
    EN_RET_CODE__NO_DESTROY_ITEM,
    EN_RET_CODE__PLAYER_NAME_RESERVE,
    EN_RET_CODE__SVR_IS_FULL,
    EN_RET_CODE__PLAYER_NOT_IN_ALLIANCE_USELESS,
    EN_RET_CODE__PLAYER_NOT_IN_ALLIANCE, //llt add@20131230,擦,与客户端保持一致
    EN_RET_CODE__ALLIANCE_NOT_EXIST,
    EN_RET_CODE__ALREADY_IN_ALLIANCE,
    // 最高经验物品使用受限
    EN_RET_CODE__MAX_KNIGHT_EXP_ITEM_LIMITED = 20040,

    EN_RET_CODE__CARD_EXP_IS_FULL = 20044,
    EN_RET_CODE__CARD_FUSE_IS_DOING = 20045,

    // occupy的对象必须是资源地，并且资源地上不能有用户或者兵力
    EN_RET_CODE__OCCUPY_COORD_INVALID = 20050,
    EN_RET_CODE__NEW_PLAYER_LIMIT = 20051,

    EN_RET_CODE__REQ_SID_ERROR = 20060,             // sid错误

    EN_RET_CODE__MARKET_IS_BUILDING = 20079,               //  在建造 market 的时候不能点 goods 查看商品
    EN_RET_CODE__TARGET_RALLY_FIELD_NOT_EXIST = 20080,

    //llt add
    EN_RET_CODE__STORE_ITEM_NOT_ENOUGH = 20101, //next
    //EN_RET_CODE__HALL_OF_WAR_NOT_EXIST,
    EN_RET_CODE__TARGET_CONSULATE_NOT_EXIST = 20102,
    EN_RET_CODE__MARKET_NOT_EXIST = 20103,

    EN_RET_CODE__RALLY_WAR_ONLY_ONE_MARCH = 20115,
    EN_RET_CODE__ALLIANCE_MEMBER_OVER_LOAD = 20117,

    EN_RET_CODE__HAVE_NO_PERMISSION = 20133,
    EN_RET_CODE__FUNCTION_NOT_OPEN = 20161,
    EN_RET_CODE__ANTI_HARASS = 20174,        // 防骚扰设置校验不通过
    EN_RET_CODE__PEACETIME_ON_NEW_PROTECT = 20194,      //在新手保护期间不能使用peacetime物品

    EN_RET_CODE__REMOVE_LAST_BARRACK_WHILE_TRAIN = 20197,
    EN_RET_CODE__REMOVE_LAST_HOSPITAL_WHILE_TREAN = 20198,

    EN_RET_CODE__DRAGON_LV_NOT_ENOUGH_PUT_ON_EQUIP = 20199,
    EN_RET_CODE__EQUIP_NOT_EXIT = 20200,
    EN_RET_CODE__EQUIP_CAN_NOT_PUT_OFF = 20201,
    EN_RET_CODE__EQUIP_UPGRADE_MATERIAL_NOT_ENOUGH = 20202,
    EN_RET_CODE__EQUIP_UPGRADE_OTHER_EQUIP_DONING = 20203,

    EN_RET_CODE__ABSORB_NOT_SAME_POS_EQUIP = 20204,
    EN_RET_CODE__ATTRIBUTE_NOT_SAME = 20205,
    EN_RET_CODE__EQUIP_NOT_HIGHTEST_LV_OR_QUANLITY = 20206,
    EN_RET_CODE__EQUIP_AGE_NOT_RIGHT = 20207,
    EN_RET_CODE__HAS_POST_ASSIST = 20208,
    EN_RET_CODE__EQUIP_UPGRADING = 20209,
    EN_RET_CODE__ABSORT_TIME_MAX = 20210,
    EN_RET_CODE__INSERT_IDX_NOT_RIGHT = 20211,
    EN_RET_CODE__CRYSTAL_NOT_ENOUGH = 20212,
    EN_RET_CODE__CRYSTAL_NOT_IN_EQUIP = 20213,
    EN_RET_CODE__EQUIP_NUM_MAX = 20214,
    EN_RET_CODE__MATERIAL_UPGRADE_NOT_ENOUGH = 20215,
    EN_RET_CODE__CRYSTAL_UPGRADE_NOT_ENOUGH = 20216,


    EN_RET_CODE__CAN_NOT_DESTROY_TIME_EFFECT_EQUIP = 20218,
    EN_RET_CODE__HOSPITAL_NOT_EXIST = 20219,
    EN_RET_CODE__REQUEST_CHANGED = 20220,
    EN_RET_CODE__ACTION_NOT_EXIST = 20221,
    EN_RET_CODE__FURE_MAX_QUANLITY_AND_LV = 20222,
    EN_RET_CODE__CAN_NOT_DESTROY_WHILE_UPGRADE = 20223,
    EN_RET_CODE__TWO_BUILDING_ACTION_DOING = 20224,


    EN_RET_CODE__HACKER = 25000,
    EN_RET_CODE__HERO_NOT_IN_CITY = 20501,
    EN_RET_CODE__ACTION_DOING_ON_YOU = 20502,
    EN_RET_CODE__NAME_INVALID = 20503,
    EN_RET_CODE__CAN_NOT_REMOVE_LAST_BUILDING = 20504,
    EN_RET_CODE__EQUIP_GRIDE_NOT_ENOUGH = 20505,
    EN_RET_CODE__CONSULATE_NOT_EXIST = 20506,
    EN_RET_CODE__CAN_NOT_USE_TO_MOVE_CRYSTAL = 20507,
    EN_RET_CODE__EQUIP_ON_PLAYER = 20508,
    EN_RET_CODE__ALLIANCE_NAME_BE_USED = 20509,
    EN_RET_CODE__ALLIANCE_NICK_BE_USED = 20510,
    EN_RET_CODE__CANNOT_MEET_THE_DEFEAT_LV = 20511,
    EN_RET_CODE__CANNOT_MOVE_CITY_BY_MARCH_ACTION = 20512,
    EN_RET_CODE__CANNOT_CHANGE_SVR_BY_CITY_NUM = 20513,
    EN_RET_CODE__COMPOSE_DRAGON_LV_NOT_ENOUGH = 20514,
    EN_RET_CODE__RALLYING_TIME_UP = 20515,
    EN_RET_CODE__EMBASSY_IS_FULL = 20516,
    EN_RET_CODE__NO_SLOT = 20517,
    EN_RET_CODE__NO_BLACKSMITH = 20518,

    EN_RET_CODE__SP_CRYSTAL_NOT_ENOUGH = 20519,
    EN_RET_CODE__SOUL_NOT_ENOUGH = 20520,
    EN_RET_CODE__PARTS_NOT_ENOUGH = 20521,
    EN_RET_CODE__DRAGON_STATUS_NOT_RIGHT_FOR_EQUIP = 20522, //被抓不能换装备
    EN_RET_CODE__TROOP_LACK = 20523,
    EN_RET_CODE__PLAYER_CHANGE_SVR = 20524, //for 称号授予
    EN_RET_CODE__SVR_CHANGE_ACTION_ERR = 20525,
    EN_RET_CODE__PEACETIME_CANT_REINFORCE = 20526,
    EN_RET_CODE__HAS_INVITED_IN_LIMIT_TIME = 20527,
    EN_RET_CODE__CAN_NOT_INVITE_TARGET = 20528,

    EN_RET_CODE__TRADE_NUM_NOT_ENOUGH = 20529, //nemo add v1.2
    EN_RET_CODE__VIOLET_GOLD_NOT_ENOUGH = 20530, //nemo add v1.2
    EN_RET_CODE__PLAYER_HAS_LEAVE_ALLIANCE = 20531, //WAVE add v1.2
    EN_RET_CODE__TRADE_HAS_BEEN_BACK = 20532, //nemo add v1.2
    EN_RET_CODE__PLAYER_CHANGE_SVR_NORMAL = 20533, //wave add v1.2
    EN_RET_CODE__ALLIANCE_NOT_EXIT_IN_THIS_SVR = 20534, //wave add v1.2
    EN_RET_CODE__PLAYER_HAS_REACH_INVITED_LIMIT = 20535, //wave add v1.2

    EN_RET_CODE__TRADE_TARGET_HAS_GONE = 20536, //nemo add v1.2
    EN_RET_CODE__SAME_TYPE_CRYSTAL = 20537,

    EN_RET_CODE__WALL_NOT_EXIST = 20538,

    EN_RET_CODE__AL_FUND_NOT_ENOUGH = 20539,

    EN_RET_CODE__CHANCELLOR_CAN_NOT_ACCEPT_INVITE = 20540,

    EN_RET_CODE__TARGET_NOT_YOUR_ALLY = 20541,

    EN_RET_CODE__ACTION_HAS_BEEN_RECALL = 20542,

    EN_RET_CODE__THRONE_RESEARCH_NOT_EXIST = 20543,

    EN_RET_CODE__PLAYER_NAME_INVALID = 20544,
    EN_RET_CODE__OTHER_NAME_INVALID = 20545,

    EN_RET_CODE__PLAYER_HAVE_NO_DRAGON = 20546,

    EN_RET_CODE__CAN_NOT_PEACETIME = 20550,
    EN_RET_CODE__RALLY_WAR_ONE_POS_ONLY_ONE_MARCH,

    EN_RET_CODE__CAN_NOT_PEACETIME_ON_SPECIAL = 20552,

    EN_RET_CODE__DRAGON_SHARD_NOT_ENOUGH = 20553,
    EN_RET_CODE__DRAGON_NOT_IN_CITY = 20554,
    EN_RET_CODE__REINFORCE_SAME_PEOPLE = 20555,

    EN_RET_CODE__FRIEND_ALLIANCE_FULL = 20556,
    EN_RET_CODE__HOSTILE_ALLIANCE_FULL = 20557,

    EN_RET_CODE__REINFORCE_ARRIVE_LIMIT = 20558,

    EN_RET_CODE__CANNOT_USER_DRAGON_SHARD = 20559,

    EN_RET_CODE__CAMP_COORD_INVALID = 20560,

    EN_RET_CODE__RALLY_REINFORCE_ARRIVE_LIMIT = 20561,

    EN_RET_CODE__HAS_KICKED_OUT = 20562,
    EN_RET_CODE__BE_KICKING_OUT = 20563,
    EN_RET_INVALID_MOVE_FIGHING = 20563,        //战斗中不能移城
    EN_RET_CODE__CANNOT_MOVE_CITY_WHEN_DRAGON_NOT_IN_CITY = 20564,

    EN_RET_CODE__CANNOT_BE_KING_WHEN_PEACE_TIME = 20565,
    EN_RET_CODE__KING_CANNOT_USE_PEACE_TIME = 20566,

    EN_RET_CODE__THRONE_NOT_YOUR_ALLY = 20567,

    EN_RET_CODE__DECORATION_OVREFLOW = 20568,

    EN_RET_CODE__TARGET_POSITION_CHANGED = 20569,

    EN_RET_CODE__ALREADY_IN_HOME_KINGDOM = 20571,
    EN_RET_CODE__TARGET_KINGDOM_CAN_NOT_IMMGRAND = 20572,
    EN_RET_CODE__KINGDOM_VS_KINGDOM_MOVE_NOT_PERMIT = 20573,

    EN_RET_CODE__DOUBLE_CRYSTAL_LV_NOT_ENOUGH = 20574,

    EN_RET_CODE__LOYALTY_LACK = 20575,

    EN_RET_CODE__CARD_ENERGY_CONSUME_REACH_LIMIT = 20576,
    EN_RET_CODE__CARD_STATUS_NOT_NORMAL = 20577,
    EN_RET_CODE__HAS_RUNE_COMPOSING = 20578,
    EN_RET_CODE__SUMMON_STONE_LACK = 20579,
    EN_RET_CODE__SUMMON_STONE_PIECE_LACK = 20580,
    EN_RET_CODE__AWAKE_MATERIAL_LACK = 20581,
    EN_RET_CODE__RUNE_PIECE_LACK = 20582,
    EN_RET_CODE__SUMMON_STONE_GRID_FULL = 20583,
    EN_RET_CODE__AWAKE_MATERIAL_GRID_FULL = 20584,
    EN_RET_CODE__RUNE_PIECE_GRID_FULL = 20585,
    EN_RET_CODE__CARD_GRID_FULL = 20586,
    EN_RET_CODE__RUNE_GRID_FULL = 20587,
    EN_RET_CODE__CARD_NOT_EXIST = 20588,
    EN_RET_CODE__RUNE_NOT_EXIST = 20589,
    EN_RET_CODE__STRENGTHEN_MATERIAL_EXCEPTION = 20590,
    EN_RET_CODE__CARD_HAS_AWOKEN = 20591,
    EN_RET_CODE__CARD_HAS_APPOINTED = 20592,
    EN_RET_CODE__RUNE_STATUS_EXCEPTION = 20593,
    EN_RET_CODE__APPOINT_CARD_SKILL_CONFLICT = 20594,
    EN_RET_CODE__CARD_ENERGY_NOT_ENOUGH = 20595,
    EN_RET_CODE__UPSTONE_LACK = 20596,
    EN_RET_CODE__UPGRADE_RUNE_FAIL = 20597,
    EN_RET_CODE__CARD_ENERGY_FULL = 20598,
    EN_RET_CODE__CARD_HAS_RUNE = 20599,
    EN_RET_CODE__RUNE_SUIT_POS_REPEAT = 20660,
    EN_RET_CODE__STRENGTHEN_BY_EVOLVE_CARD = 20661,
    EN_RET_CODE__SUMMON_STONE_PIECE_GRID_FULL = 20662,
    EN_RET_CODE__CARD_EXP_LACK = 20663,
    EN_RET_CODE__REMAIN_LACK = 20664,
    EN_RET_CODE__TRIAL_ITEM_ALREAD_COLLECTED = 20665,
    EN_RET_CODE__NO_SELECT_RUNE_TO_SALE = 20666,
    EN_RET_CODE__DUNGEON_TRIAL_ENERGY_LACK = 20667,
    EN_RET_CODE__PVP_ENERGY_LACK = 20668,
    EN_RET_CODE__PVP_HONOR_POINT_LACK = 20669,
    EN_RET_CODE__RALLY_LAIR_ENERGY_LACK = 20670,
    EN_RET_CODE__SWEEP_ENERGY_LACK = 20671,
    EN_RET_CODE__EVOLVE_TOKEN_LACK = 20672,
    EN_RET_CODE__CARD_EGG_NOT_ENOUGH = 20673, // 未获得该龙蛋
    EN_RET_CODE__CARD_MEDAL_LACK = 20674, // 龙勋章不足
    EN_RET_CODE__OTHER_CARD_DO_GROWTHING = 20675, // 其他龙正在升品中
    EN_RET_CODE__ITEM_SOLD_OUT = 20676,  // 道具购买次数已达上限
    EN_RET_CODE__TROPHY_NOT_ENOUGH = 20677, // 战利品不足
    EN_RET_CODE__TROPHY_PIECE_NOT_ENOUGH = 20678, // 战利品碎片不足
    EN_RET_CODE__TROPHY_BOOK_NOT_ENOUGH = 20679, // 战利品合成书不足
    EN_RET_CODE__TROPHY_BOOK_PIECE_NOT_ENOUGH = 20680, // 战利品合成书碎片不足

    EN_RET_CODE__PLAY_CARD_ALREADY_START = 20681,
    EN_RET_CODE__PLAY_CARD_LACK_DIAMOND = 20682,

    EN_RET_CODE__TEN_POWER_SHOOT_MODE_NOT_UNLOCKED = 20683, // 10倍射击模式未解锁
    EN_RET_CODE__LACK_OF_BULLET = 20684, // 子弹不足

    EN_RET_CODE__SET_HIVE_COORD_INVALID = 20685,

    EN_RET_CODE__DRAGON_SUICIDE_NOT_IN_PRISON_TIME = 20686,
    EN_RET_CODE__DRAGON_SUICIDE_PRISON_TIME_NOT_ENOUGH = 20687,

    EN_RET_CODE__CANNOT_REINFORCE_PEACE_THRONE = 20688,
    EN_RET_CODE__CANNOT_REINFORCE_PEACE_FORTRESS = 20689,
    EN_RET_CODE__CANNOT_REINFORCE_PEACE_STRONGHOLD = 20690,

    EN_RET_CODE__COMMANDER_CANNOT_PEACE_TIME_IN_WAR = 20691,

    EN_RET_CODE__FORTRESS_NOT_YOUR_ALLY = 20693, // 要塞不属于你的联盟
    EN_RET_CODE__STRONGHOLD_NOT_YOUR_ALLY = 20694, // 据点不属于你的联盟

    EN_RET_CODE__DISCOUNT_SHOP_LIMIT_LACK = 20696, // 限购次数不足
    EN_RET_CODE__DISCOUNT_SHOP_NOT_OPEN = 20697, // 活动已过期

    EN_RET_CODE__NOT_JOIN_AVA_BATTLE = 20698, //没有在ava 战斗列表，没有参加ava战斗
    EN_RET_CODE__AVA_BATTLE_BUILDING_STATE_NOT_YOUR_ALLY = 20699, //ava 州府不属于你联盟
    EN_RET_CODE__AVA_BATTLE_BUILDING_RED_FORTRESS_NOT_YOUR_ALLY = 20700, //ava 红色要塞不属于你联盟
    EN_RET_CODE__AVA_BATTLE_BUILDING_BLUE_FORTRESS_NOT_YOUR_ALLY = 20701, //ava 蓝色要塞不属于你联盟
    EN_RET_CODE__AVA_BATTLE_BUILDING_STRONGHOLD_NOT_YOUR_ALLY = 20702, //ava 据点不属于你联盟
    EN_RET_CODE__AVA_BATTLE_BUILDING_ATK_DEF_TOWER_NOT_YOUR_ALLY = 20703, //ava 攻防塔不属于你联盟
    EN_RET_CODE__AVA_BATTLE_BUILDING_MILITARY_STATION_NOT_YOUR_ALLY = 20704, //ava 军需站不属于你联盟
    EN_RET_CODE__AVA_BATTLE_BUILDING_CLOCK_TOWER_NOT_YOUR_ALLY = 20705, //ava 钟楼不属于你联盟
    EN_RET_CODE__AVA_BATTLE_BUILDING_MARCHING_STATION_NOT_YOUR_ALLY = 20706, //ava 行军驿站不属于你联盟

    EN_RET_CODE__AVA_BATTLE_BUILDING_STATE_ALREADY_ASSIGNED_COMMANDER = 20707, //ava 州府已经有commander
    EN_RET_CODE__AVA_BATTLE_BUILDING_RED_FORTRESS_ALREADY_ASSIGNED_COMMANDER = 20708, //ava 红色要塞已经有commander
    EN_RET_CODE__AVA_BATTLE_BUILDING_BLUE_FORTRESS_ALREADY_ASSIGNED_COMMANDER = 20709, //ava 蓝色要塞已经有commander
    EN_RET_CODE__AVA_BATTLE_BUILDING_STRONGHOLD_ALREADY_ASSIGNED_COMMANDER = 20710, //ava 据点已经有commander
    EN_RET_CODE__AVA_BATTLE_BUILDING_ATK_DEF_TOWER_ALREADY_ASSIGNED_COMMANDER = 20711, //ava 攻防塔已经有commander
    EN_RET_CODE__AVA_BATTLE_BUILDING_MILITARY_STATION_ALREADY_ASSIGNED_COMMANDER = 20712, //ava 军需站已经有commander
    EN_RET_CODE__AVA_BATTLE_BUILDING_CLOCK_TOWER_ALREADY_ASSIGNED_COMMANDER = 20713, //ava 钟楼已经有commander
    EN_RET_CODE__AVA_BATTLE_BUILDING_MARCHING_STATION_ALREADY_ASSIGNED_COMMANDER = 20714, //ava 行军驿站已经有commander
    EN_RET_CODE__AVA_BATTLE_MOVE_TO_BATTLE_FIELD_NOT_PERMIT = 20715,

    EN_RET_CODE_AVA_SIGNUP_ALLIANCE_CREATE_TIME_NOT_MEET_REQUIREMENT = 20716, //ava 报名，联盟创建时间未能满足要求
    EN_RET_CODE_AVA_SIGNUP_ALLIANCE_FORCE_RANK_NOT_MEET_REQUIREMENT = 20717, //ava 报名，联盟兵力排名未能满足要求
    EN_RET_CODE_AVA_SIGNUP_TOO_MUCH_ATTEND_USERS = 20718, //ava 报名, 修改参赛成员列表，人数超限


    EN_RET_CODE__AVA_BATTLE_NOT_BALANCE = 20720, //活动还未结算
    EN_RET_CODE__AVA_BATTLE_NOT_ATTEND = 20721, //未参与活动
    EN_RET_CODE__AVA_BATTLE_HAS_CLAIMED_REWARD = 20722, //已领奖
    EN_RET_CODE__AVA_BATTLE_NOT_EXIST = 20723, //活动不存在
    EN_RET_CODE__AVA_BATTLE_NOT_IN_BATTLE_SVR = 20724, //不在战场服
    EN_RET_CODE__AVA_BATTLE_IN_BATTLE_SVR = 20725, //当前处于战场服
    EN_RET_CODE__AVA_BATTLE_READY_STAGE = 20726, //当前处于准备阶段

    EN_RET_CODE_AVA_BATTLE_MOVE_IN_CANT_MOVE_CITY_WITH_REINFORCE = 20728, //ava 进入战场，无法移动因为还有友军驻扎
    EN_RET_CODE_AVA_BATTLE_MOVE_IN_CANT_MOVE_CITY_WITH_INCOMMING_ATK_MARCH = 20729, //ava 进入战场，有进攻队列正在靠近，无法移动
    EN_RET_CODE_AVA_BATTLE_MOVE_OUT_CANT_MOVE_CITY_WITH_REINFORCE = 20730,//ava 移出战场，有联盟驻军无法移动
    EN_RET_CODE_AVA_BATTLE_MOVE_OUT_CANT_MOVE_CITY_WITH_INCOMMING_ATK_MARCH = 20731,//ava 移出战场，有进攻队列正在靠近，无法移动
    EN_RET_CODE_AL_DIPLOMACY_COMMENT_ONE_DAY_LIMIT = 20732, // 同一玩家在一天内对同一联盟发布外交留言条数的最大值

    EN_RET_CODE_AL_YOU_ARE_NOT_IN_THE_AVA_COMPETITION_LIST = 20733, //没有在参赛列表
    EN_RET_CODE_AL_NOT_IN_THE_APPROPRIATE_AVA_EVENT_TIME = 20734, //没有在活动战斗期间
    EN_RET_CODE_AL_YOU_ARE_AREALDY_IN_THE_AVA_MAP_SVR = 20735,//你已经在svr里面了

    EN_RET_CODE_AL_AVA_MOVE_CITY_INSIDE_LACK_OF_MOVE_TIMES = 20736,//ava 移城次数不足

    EN_RET_CODE__REVIVE_TROOP_AMRY_NOT_ENOUGH = 20737,//复活军队数量不够
    EN_RET_CODE__REVIVE_TROOP_ACTION_NOT_ENOUGH = 20738,//等待复活队列已满
    EN_RET_CODE__REVIVE_TROOP_ACTION_NOT_EXIST = 20739,//队列不存在

    EN_RET_CODE__AL_DEPARTMENT_NAME_EXIST = 20740,
    EN_RET_CODE__AL_DEPARTMENT_NOT_EXIST = 20741,
    EN_RET_CODE__AL_DEPARTMENT_IN_ANOTHER_DEPARTMENT = 20742,
    EN_RET_CODE__AL_DEPARTMENT_NOT_IN_THIS_DEPARTMENT = 20743,
    EN_RET_CODE__AL_DEPARTMENT_NUM_BEYOND_LIMIT = 20744,
    EN_RET_CODE__AL_DEPARTMENT_NOT_HAVE_PRIVILEGE = 20745,

    EN_RET_CODE__PLAN_SIZE_REACH_MAX = 20746, //超过最大预设数量
    EN_RET_CODE__PLAN_LOCK = 20747, //预设未解锁

    EN_RET_CODE__EVIP_HAS_ALREADY_ACTIVATED = 20748,
    EN_RET_CODE__EVIP_ACTIVE_POINT_IS_NOT_ENOUGH = 20749,
    EN_RET_CODE__GET_EVIP_INFO_FAIL = 20750,

    EN_RET_CODE__WAR_FEVER_CANNOT_PEACETIME = 20751,
    EN_RET_CODE__WAR_FEVER_CANNOT_NEW_PLAYER_MOVE_CITY = 20752,
    EN_RET_CODE__WAR_FEVER_CANNOT_IMMIGRANT = 20753,
    EN_RET_CODE__OFFLINE_DEFENCE_COMPENSATION_NO_REWARD = 20754,
    EN_RET_CODE__CANNOT_SET_AL_HIVE_IS_OTHER_SVR = 20755,
    EN_RET_CODE__AVA_COMPETITIONS_HAS_ALREADY_ADD = 20756,
    EN_RET_CODE__AVA_COMPETITIONS_HAS_ALREADY_DEL = 20757,

    EN_RET_CODE__COWBOY_NOT_EXISTS = 20758,
    EN_RET_CODE__COWBOY_HAS_ALREADY_UNLOCK = 20759,
    EN_RET_CODE__COWBOY_HAS_NOT_UNLOCK_YET = 20760,
    EN_RET_CODE__COWBOY_PIECE_IS_NOT_ENOUGH = 20761,
    EN_RET_CODE__COWBOY_SKILL_ITEM_IS_NOT_ENOUGH = 20762,
    EN_RET_CODE__COWBOY_IS_MAX_STAR = 20763,
    EN_RET_CODE__COWBOY_SKILL_IS_MAX_LV = 20764,

    EN_RET_CODE__AD_DAY_LIMIT = 20765,
    EN_RET_CODE__NOT_UNACOMMPOLISHED_YET = 20766,
    EN_RET_CODE__HAS_ALREADY_COMMPOLISHED = 20767,
    EN_RET_CODE__OWN_NUM_ZERO = 20768,
    EN_RET_CODE__ALLIANCE_CANNOT_KICK_DURING_BANDIT_ATTACK = 20769,
    EN_RET_CODE__OPERATION_FAIL_DURING_BANDIT_ATTACK = 20770,
    EN_RET_CODE__START_BANDIT_ATTACK_FAIL = 20771,

    EN_RET_CODE__COWBOY_EXP_LIMIT = 20772,
    EN_RET_CODE__FORTREES_NOT_EXITS_WHILE_DONATION = 20773,
    EN_RET_CODE__FORTREES_NOT_EXITS_WHILE_RESET_OWN_NUM = 20774,
    EN_RET_CODE__STILL_REMAIN_OWN_NUM = 20775,
    EN_RET_CODE__ONLY_ONE_MARCH_CAN_OCCUPY_AL_RSS = 20776,

    EN_RET_CODE__NOT_AL_FORTRESS_COMMANDER = 20777, //不是联盟堡垒指挥官
    EN_RET_CODE__AL_FORTRESS_COMMANDER_EXIST = 20778, //联盟指挥官已存在
    EN_RET_CODE__CANNOT_BE_AL_FORTRESS_COMMANDER = 20779, //不能成为联盟指挥官
    EN_RET_CODE__AL_BUILDING_NOT_BELONGS_TO_YOUR_ALLIANCE = 20780, //此联盟建筑不属于你的联盟
    EN_RET_CODE__CANNOT_REINFORCE_THE_AL_FORTRESS_ON_PEACE_TIME = 20781, //联盟堡垒peace_time时, 不可被支援
    EN_RET_CODE__CANNOT_STORAGE_RSS_AS_REACH_FINAL_STORAGE_LIMIT = 20782, //无法存储资源, 已到达个人存储总量
    EN_RET_CODE__CANNOT_STORAGE_RSS_AS_REACH_DAILY_STORAGE_LIMIT = 20783, //无法存储资源, 个人今日存储量已耗尽
    EN_RET_CODE__CANNOT_GET_RSS_FROM_AL_WAREHOUSE_AS_RSS_LACK = 20784, //无法提取资源, 仓库资源不足
    EN_RET_CODE__AL_FORTRESS_NOT_FINISH = 20785, //帮派要塞未建造完成
    EN_RET_CODE__AL_BUILDING_INVALID = 20786, //联盟建筑已失效

    EN_RET_CODE__AL_BUILDING_CAN_NOT_BUILD_ON_SPECIAL = 20787,     //存在非法地形，不能建造或移动联盟建筑
    EN_RET_CODE__AL_BUILDING_ONLY_ONE_FORTRESS = 20788,    //不能重复建造堡垒
    EN_RET_CODE__AL_BUILDING_NOT_VALID_FORTRESS = 20789,    //不存在建成的堡垒
    EN_RET_CODE__AL_BUILDING_NOT_IN_HIVE_RANGE = 20790,    //不在聚集地范围内
    EN_RET_CODE__AL_BUILDING_REMOVING = 20791,    //正在拆除该联盟建筑
    EN_RET_CODE__AL_BUILDING_BUILDING = 20792,    //正在建造该联盟建筑
    EN_RET_CODE__AL_BUILDING_ALREADY_BUILT = 20793,    //已存在该联盟建筑
    EN_RET_CODE__AL_BUILDING_OTHER_BUILDING = 20794,    //存在正在建造的联盟建筑
    EN_RET_CODE__AL_BUILDING_STATUS_NOT_BUILD = 20795,    //仅能援助建造正在建造中的联盟建筑
    EN_RET_CODE__AL_BUILDING_PUT_ON_REINFORCE_REACH_MAX_TROOP_NUM = 20796,    //超过援助建造军队数量上限
    EN_RET_CODE__AL_BUILDING_MOVE_REACH_MAX_TIME = 20797,    //超过每日移动联盟建筑上限
    EN_RET_CODE__AL_BUILDING_MEMBER_NOT_ENOUGH = 20798,    //联盟成员不足，无法建造联盟堡垒
    EN_RET_CODE__AL_RESEARCH_UPGRADE_NOT_VICE_OR_CHANCELLOR = 20799,    //科技升级时，用户不是盟主或副盟主
    EN_RET_CODE__AL_RESEARCH_UPGRADE_MAX_LEVEL = 20800,    //科技升级时，科技等级已满
    EN_RET_CODE__AL_RESEARCH_UPGRADE_STAGE_NOT_MAX = 20801,    //科技升级时，科技阶段未满
    EN_RET_CODE__AL_RESEARCH_RECOMMEND_MAX_NUM = 20802,    //科技推荐时，推荐数量已满
    EN_RET_CODE__AL_RESEARCH_RECOMMEND_NOT_VICE_OR_CHANCELLOR = 20803,    //科技推荐时，用户不是盟主或副盟主
    EN_RET_CODE__AL_RESEARCH_DONATION_NO_ENOUGH_OWN_NUM = 20804,    //科技捐赠时，无剩余可用捐赠次数
    EN_RET_CODE__AL_RESEARCH_DONATION_MAX_PROGRESS = 20805,    //科技捐赠时，已经达到最大进度
    EN_RET_CODE__RESEARCH_UPGRADE_QUEUE_MAX = 20806, //科技升级队列已满
    EN_RET_CODE__AL_RESEARCH_DUPLICATE_ACTION = 20807, //已存在相同的研究在研究队列中
    //EN_RET_CODE__AL_BUILDING_MAP_NOT_NORMAL = 20808, //地形内无法建造联盟建筑
    EN_RET_CODE__AL_BUILDING_CAN_NOT_REMOVE = 20809, //仅和平时期可拆除联盟建筑

    EN_RET_CODE__AL_BUILDING_SUPER_RSS_LITE_NOT_PEACE_FOR_OCCUPY = 20811, //仅和平时期可采集

    EN_RET_CODE__AL_RESEARCH_DONATION_NOT_AL_MEMBER = 20812, //科技捐赠时不是联盟成员
    EN_RET_CODE__AL_RESEARCH_DONATION_CURR_STAGE_COMPLETED = 20813, //客户端发送的stage和数据库的stage不符合(捐赠时发生了升阶段)

    EN_RET_CODE__AL_BUILDING_CAN_NOT_MOVE_NOT_PEACE = 20815, //仅和平时期可移动联盟建筑
    EN_RET_CODE__AL_BUILDING_SUPER_RSS_LITE_ALREADY_CLEAN = 20816, //超级资源地被采空

    EN_RET_CODE__IMMIGRANT_GET_RANK_FAILED = 20817, //获取排名失败
    EN_RET_CODE__IMMIGRANT_RANK_CHANGED = 20818, //排名有变化，消耗不一致，不能移民
    EN_RET_CODE__IMMIGRANT_RESOURCE_EXCEED = 20819, //资源超出限额，不能移民
    EN_RET_CODE__IMMIGRANT_IN_ALLIANCE = 20820, //在联盟内，不能移民
    EN_RET_CODE__IMMIGRANT_IN_KVK = 20821, //KVK期间，不能移民

    EN_RET_CODE__AL_LEGION_BATTLE_NOT_COMMANDER = 20822, //不是指挥官
    EN_RET_CODE__AL_LEGION_BATTLE_NOT_ALLIANCE_OFFICER = 20823, //不是联盟官员
    EN_RET_CODE__AL_LEGION_BATTLE_CITY_NOT_NEAR_BY = 20824, //不能攻打或侦查非相邻城市
    EN_RET_CODE__AL_LEGION_BATTLE_BUILDING_NOT_BELONG_SELF = 20825, //地形不属于本联盟
    EN_RET_CODE__AL_LEGION_BATTLE_NOT_IN_BATTLE_FEILD = 20826, //不在战场内
    EN_RET_CODE__AL_LEGION_BATTLE_TARGET_CAN_NOT_MOVE = 20827, //无法移城至目标地
    EN_RET_CODE__AL_LEGION_BATTLE_MOVE_NOT_COLD_DOWN = 20828, //移城CD未冷却
    EN_RET_CODE__AL_LEGION_BATTLE_CANNOT_ATTACK_CITY = 20829, //不能攻打玩家(不能攻打不在附属地或附属地所属城市不相邻的玩家)

    EN_RET_CODE__AL_LEGION_DISMISS_LEGION_WHILE_EVENT = 20830,
    EN_RET_CODE__AL_LEGION_DISMISS_LEGION_NOT_ENOUGH_POS = 20831,
    EN_RET_CODE__AL_LEGION_CAN_NOT_DISMISS_LEGION = 20832,
    EN_RET_CODE__AL_LEGION_CAN_NOT_CHANGE_MEMBER_AFTER_ENROLL_END = 20833,
    EN_RET_CODE__AL_LEGION_MAX_MEMBER_NUM = 20834,
    EN_RET_CODE__AL_LEGION_HAS_COMMANDER = 20835,
    EN_RET_CODE__AL_LEGION_MANAGE_NOT_ENOUGH_POS = 20836,
    EN_RET_CODE__AL_LEGION_MANAGE_BELONG_ANOTHER_LEGION = 20837,
    EN_RET_CODE__AL_LEGION_CAN_NOT_ENROLL = 20838,
    EN_RET_CODE__CAN_NOT_LEAVE_AL_AT_WAR = 20839,

    EN_RET_CODE__AL_LEGION_HAS_EXITS_NAME = 20841,
    EN_RET_CODE__AL_LEGION_CAN_NOT_CAHNGE_NAME_AFTER_SIGN = 20842,
    EN_RET_CODE__AL_LEGION_NOT_MEMBER_WHILE_CONFIRM_RESULT = 20843,
    EN_RET_CODE__AL_LEGION_NOT_REWARD = 20844,
    EN_RET_CODE__AL_LEGION_COMMANDER_ONLY_CAN_BE_DISPOSE = 20845,
    EN_RET_CODE__CANNOT_ASSIGN_WITHOUT_SHERIFF = 20846, //行军没有治安官或牛仔，不能派遣指挥官队列
    EN_RET_CODE__CANNOT_ASSIGN_AGAIN = 20847, //正在攻打或已派出指挥官队列，无法再次派出

    EN_RET_CODE__COMMANDER_CANNOT_PEACE_TIME_IN_BATTLE = 20848, //在AVA战场中，指挥官无法开罩
    EN_RET_CODE__CAN_NOT_KICK_AL_MEMBER_AT_WAR = 20849,    //无法踢出在军团战场中的盟友

    EN_RET_CODE__Al_SHAMA_MAX_TEAM_MEMBER_NUM = 20850,    //刹马镇小队人数已经达上限
    EN_RET_CODE__Al_SHAMA_CHANLLENG_HAS_BEGIN = 20851,    //刹马镇小队已开启试炼
    EN_RET_CODE__Al_SHAMA_NOT_UNLOCK_DIFFICULTY = 20852,    //刹马镇玩家未解锁对应难度
    EN_RET_CODE__Al_SHAMA_CASTLE_LV_NOT_MATCH_DIFFICULTY = 20853,    //刹马镇玩家主城等级不符合试炼难度要求
    EN_RET_CODE__Al_SHAMA_CAN_NOT_CHANGE_MEMBER = 20854,    //刹马镇只有试炼开启前可以更改小队成员
    EN_RET_CODE__Al_SHAMA_EXPIRED_TEAM = 20855,    //刹马镇小队已失效

    EN_RET_CODE__SHAMA_BATTLE_HAS_NO_TEAM = 20856,    //没有小队
    EN_RET_CODE__SHAMA_BATTLE_NOT_EXIST_TEAM = 20857,    //不存在的小队
    EN_RET_CODE__SHAMA_BATTLE_START_NOT_ENOUGH_MEMBER = 20858,    //开启刹马镇试炼人数不足
    EN_RET_CODE__SHAMA_BATTLE_IN_EVENT_PROGRESS = 20859,    //已开启活动
    EN_RET_CODE__SHAMA_BATTLE_NOT_EXIST_DIFFICULTY = 20860,    //不存在的难度
    EN_RET_CODE__SHAMA_BATTLE_NO_AVAILABLE_BATTLEFIELD = 20861,    //当前无可用战场, 稍后再试...
    EN_RET_CODE__SHAMA_BATTLE_NOT_TEAM_LEADER = 20862,    //不是小队队长
    EN_RET_CODE__SHAMA_BATTLE_SHAMA_BUILDING_DESTROYED = 20863, //NPC主城已被摧毁
    EN_RET_CODE__SHAMA_BATTLE_EVENT_END = 20864, //刹马镇活动已结束

    EN_RET_CODE__SHAMA_TOWER_NOT_BELONG_SELF = 20865, //刹马镇炮塔不属于自己联盟
    EN_RET_CODE__SHAMA_TOWER_NOT_COMMANDER = 20866,   //不是刹马镇炮塔的指挥官
    EN_RET_CODE__SHAMA_BATTLE_JOIN_END = 20867,        //不在刹马镇试炼可开启时间内
    EN_RET_CODE__SHAMA_BATTLE_CAN_NOT_LEAVE_AL_WHILE_IN_TEAM = 20868,        //有小队状态下不允许退出联盟

    //兑换商店错误码 v2.4.1
    EN_RET_CODE__EXCHANGESHOP_GOODS_NOT_EXIST = 20869,    //物品不存在
    EN_RET_CODE__EXCHANGESHOP_AMOUNT_LIMITED = 20870,     //购买数量已用完
    EN_RET_CODE__EXCHANGESHOP_TOKEN_NOT_ENOUGH = 20871,   //兑换币不足
    EN_RET_CODE__EXCHANGESHOP_COIN_NOT_ENOUGH = 20872,    //金币不足
    EN_RET_CODE__EXCHANGESHOP_ITEM_NOT_ENOUGH = 20873,    //道具不足

    //大帝赠送奖励 v2.5
    EN_RET_CODE__EMPEROR_SEND_REWARD_REPEATED = 20874,          // 已经给玩家赠送过,不能再赠送
    EN_RET_CODE__EMPEROR_SEND_REWARD_GIFT_NO_EXIST = 20875,     // 奖励物品不存在
    EN_RET_CODE__EMPEROR_SEND_REWARD_GIFT_NUM_LIMITED = 20876,  // 奖励已经送完了


    EN_RET_CODE__SUPER_BUILDING_ALREADY_ASSIGNED_COMMANDER = 20877,
    EN_RET_CODE__SUPER_BUILDING_NOT_YOUR_ALLY = 20878,
    EN_RET_CODE__CANNOT_REINFORCE_PEACE_SUPER_BUILDING = 20879,
    EN_RET_CODE__ALREADY_HAS_KINGDOM_TITLE = 20880,
    EN_RET_CODE__ALREADY_USED_TITLE = 20881,
    EN_RET_CODE__ALREADY_USED_KINGDOM_TITLE = 20882,

    EN_RET_CODE__SKVK_SCHEDULE_CHECK_FAIL = 20883,  //超级王座活动配置拉取失败
    EN_RET_CODE__MOBILIZE_DONATE_NUM_LACK = 20884,  //超级王座 全国动员捐赠次数不足
    EN_RET_CODE__MOBILIZE_EXCEED_BUY_LIMIT = 20885, //超级王座 全国动超出今日购买捐赠次数上限
    EN_RET_CODE__ENCOURAGE_TIMES_LACK = 20886,      //超级王座 助威次数不足

    EN_RET_CODE__SKVK_CANNOT_MOVE_CITY = 20887,      //超级王座仅争夺期可进行移城
    EN_RET_CODE__SKVK_MOVE_CITY_CASTLE_LV_LIMIT = 20888,      //超级王座移城等级不够

    EN_RET_CODE__CAN_ONLY_MOVE_TO_NORMAL_SVR = 20889,      //不能永久移城至活动服

    EN_RET_CODE__CANNOT_BUILD_AL_BLACKMARKET_IN_SPECIAL_MAP = 20891,
    EN_RET_CODE__ATK_AL_BLACKMARKET_ENOUGH = 20892,
    EN_RET_CODE__CANNOT_ATK_AL_BLACKMARKET = 20893,
    EN_RET_CODE__AL_BLACKMARKET_SCHEDULE_IS_EXPIRE = 20894,
    EN_RET_CODE__CANNOT_BUY_AL_BLACKMARKET = 20895,
    EN_RET_CODE__EXCEED_AL_BLACKMARKET_BUY_TIMES = 20896,

    EN_RET_CODE__HAS_ALREADY_BUILD_AL_BLACKMARKET = 20897,
    EN_RET_CODE__NOT_CANNOT_BUILD_AL_BLACKMARKET_NOT_IN_TIME = 20898,
    EN_RET_CODE__NOT_CANNOT_BUILD_AL_BLACKMARKET_AL_POS = 20899,
    EN_RET_CODE__NOT_AL_ACTIVE_POINT_NOT_ENOUGH = 20900,
    EN_RET_CODE__AL_BLACKMARKET_BUY_NEED_IS_NOT_ENOUGH = 20909,

    EN_RET_CODE__AUCTION_ALREADY_ADMISSION = 20901, //玩家已经入场拍卖场
    EN_RET_CODE__AUCTION_NOT_ADMISSION = 20902, //玩家没有入场拍卖场
    EN_RET_CODE__AUCTION_NOT_BEGIN = 20903, //拍卖场未开始
    EN_RET_CODE__AUCTION_FINISH = 20904, //拍卖场已经结束
    EN_RET_CODE__AUCTION_PRICE_NOT_ENOUGH = 20905, //出价不够
    EN_RET_CODE__AUCTION_ADMISSION_FEE_INVALID = 20906,

    EN_RET_CODE__SKIN_PIECE_NUM_NOT_ENOUGH = 20907, //皮肤碎片合成数量不足

    EN_RET_CODE__CAN_NOT_DISMISS_ALLIANCE_WITH_BLACKMARKET = 20908,

    EN_RET_CODE__CHAT_FRIEND_SP_NODE_NUM_LIMIT = 20912,
    EN_RET_CODE__CHAT_FRIEND_NOTI_SWITCH_NUM_LIMIT,
    EN_RET_CODE__CHAT_GROUP_CHANNEL_NOT_EXIST,
    EN_RET_CODE__CHAT_GROUP_CREATE_OR_INVITE_FAIL,
    EN_RET_CODE__CHAT_GROUP_OWNER_CANNOT_LEAVE,
    EN_RET_CODE__CHAT_GROUP_SP_NODE_NUM_LIMIT,
    EN_RET_CODE__CHAT_GROUP_NOTI_SWITCH_NUM_LIMIT,
    EN_RET_CODE__CHAT_GROUP_MEMBER_SIZE_LIMIT,
    EN_RET_CODE__CHAT_IN_OTHER_BLOCK_LIST,
    EN_RET_CODE__CHAT_IN_YOUR_BLOCK_LIST,
    EN_RET_CODE__CHAT_INVITE_EXPIRED,
    EN_RET_CODE__CHAT_IS_FRIEND,
    EN_RET_CODE__CHAT_IS_NOT_BELONG_THIS_GROUP,
    EN_RET_CODE__CHAT_IS_NOT_FRIEND,
    EN_RET_CODE__CHAT_IS_NOT_GROUP_OWNER,
    EN_RET_CODE__CHAT_NOT_ADD_YOURSELF,
    EN_RET_CODE__CHAT_SELF_FRIEND_NUM_LIMIT,
    EN_RET_CODE__CHAT_SELF_GROUP_NUM_LIMIT,
    EN_RET_CODE__CHAT_TARGET_FRIEND_NUM_LIMIT,
    EN_RET_CODE__CHAT_TARGET_INVITE_LIST_NUM_LIMIT,
    EN_RET_CODE__USER_INPUT_CONTENT_INCLUDE_SENSETIVE_WORDS = 20932,
    EN_RET_CODE__THE_TROOP_IS_RETURN_TO_CITY = 20937,          // 该队列已回城。。。

    EN_RET_CODE__ALL_INVITE_FAIL_WHEN_CREATE_GROUP = 20943,
    EN_RET_CODE__ALL_INVITE_FAIL_WHEN_INVITE_MEMBER = 20944,

    EN_RET_CODE__PVP_NOT_OPEN_YET = 21100,
    EN_RET_CODE__PVP_DURING_SEASON_BREAK = 21101,
    EN_RET_CODE__SUPER_MAN_REWARD_HAS_CLAIMED = 21102,

    EN_RET_CODE__MOVE_CITY_WRONG_POS = 21104,   // 目的地无法进行移城
    EN_RET_CODE__MOVE_CITY_COLLISION = 21105,   // 目的地周围有碰撞
    EN_RET_CODE__MOVE_CITY_POS_NOT_IN_AL_TERRITORY = 21106,     // 领土移城时 未在领土范围内
    EN_RET_CODE__MOVE_CITY_CANNOT_CROSS_BARRIER = 21107,       // 跨关卡移城，关卡不属于自己的联盟

    EN_RET_CODE__RAID_NOT_EXIST = 21108,
    EN_RET_CODE__NEW_TARGET_NOT_EXIST = 21109,
    EN_RET_CODE__VILLAGE_IS_SCOUTED = 21110,
    EN_RET_CODE__POS_NO_FOG         = 21111,
    EN_RET_CODE__ENERGY_NOT_ENOUGH  = 21113,
    EN_RET_CODE__VEIN_IS_FIGHTING   = 21120,
    EN_RET_CODE__NOT_THE_SAME_ALLIANCE = 21128,
    EN_RET_CODE__TRANSPORT_SLOT_LACK = 21129,
    EN_RET_CODE__RAID_NO_TROOPS = 21130, // 副本士兵数量不足
    EN_RET_CODE__TARGET_IS_DEAD = 21131,
    EN_RET_CODE__EVENT_BUSY = 21133, //活动繁忙
	EN_RET_CODE__PLAYER_CANT_GET_TITLE = 21134, // 玩家无法接受头衔
    EN_RET_CODE__PM_NO_VILLAGE = 21138, // 保护物资活动中，附近无村庄
    EN_RET_CODE__PM_VILLAGE_ALL_BE_USED = 21139, // 保护物资活动中，附近无可用的村庄
    EN_RET_CODE__POS_CANT_REACH = 21150, // 目标点不可达
    EN_RET_CODE__HAS_REIN = 21151, // 城内有增援(如果要用这个错误码，要给客户端说一下)
    EN_RET_CODE__EVENT_TASK_HAS_BEEN_ACCEPTED = 21154, //活动任务已被他人领取
    EN_RET_CODE__AVA_PRACTICE_SKILL_CANNOT_CHANGE = 21156, //AVA练习赛，超过可修改时间已无法修改技能
    EN_RET_CODE__AVA_REINFORCE_WHEN_FULL = 21157, //AVA_建筑满队列后增援报错

    EN_RET_CODE__RALLY_WAIT_JOIN    = 27007,
    EN_RET_CODE__KINGDOM_SKILL_UNAVAILABLE = 27017,
    EN_RET_CODE__EVENT_NO_AL_NUM = 27019,
    EN_RET_CODE__BOSS_TRAP_CAN_NOT_REMOVE = 27022,  // 干扰陷阱建筑不可拆除
    EN_RET_CODE__NO_VALID_RIFT_POS = 27024, // 暂无合理地块生成裂缝
    EN_RET_CODE__NO_VALID_VILLAGE_POS = 27025, // 抱歉，你城堡的所在位置范围内没有合适的村庄终点
    EN_RET_CODE__CAN_FREE_EXCUTE_LORD = 27030, // 领主已进入处决期
    EN_RET_CODE__AVA_HAVE_OUTPUT_TROOP = 27032,      // 有在外部队不能进入AVA
    EN_RET_CODE__AVA_HAVE_WOUNDED = 27033,      // 有伤兵不能进入AVA
    EN_RET_CODE__AVA_HAVE_WAR_FEVER = 27034,      // 有战争狂热不能进入AVA
    EN_RET_CODE__AVA_HAVE_HOSPITAL_QUEUE = 27035,      // 有治疗队列不能进入AVA
    EN_RET_CODE__AVA_FULL = 27036,      // 战场满人不能进入AVA
    EN_RET_CODE__AVA_NOT_JOINER = 27037,      // 非报名人员不能进入AVA
	EN_RET_CODE__AVA_NOT_TOPN_ALLIANCE = 27038, // 非该服的TopN联盟
    EN_RET_CODE__AVA_PRACTICE_ALREADY_REGISTER_CANNOT_CHANGE = 27039, // AVA练习赛已报名不允许修改
    EN_RET_CODE__AVA_BATTLE_TIME_INDEX_CHOOSE_RUN_OUT = 27040, // AVA练习赛该时段的名额都用完了
    EN_RET_CODE__AVA_PACTICE_IN_COLDDOWN = 27041, //AVA练习赛,上一次练习时间距今未超过冷却期
    EN_RET_CODE__AVA_BATTLEFIELD_IS_OVER = 27042, //AVA战场已经结束
    EN_RET_CODE__CAN_NOT_DISMISS_ALLIANCE_DURING_KVK = 27049, //kvk 争夺期期间，不能解散联盟


    // kvk
    EN_RET_CODE__KVK_LORD_BE_ARREST = 27043,        // 龙被抓了不能跨服移城
    EN_RET_CODE__KVK_HAS_OUTSIDE_TROOP = 27045,     // 有在外部队不能跨服移城

    EN_RET_CODE__INTEL_IS_NOT_YOURS = 28001,
    EN_RET_CODE__EXPEDITION_INTEL_IS_AIMED = 28002, // 征伐情报已被指定
    EN_RET_CODE__TARGET_IS_ALLY = 28003,            // 目标是友军
    EN_RET_CODE__NO_SUITABLE_POS = 28005,            // 无位置可生成干扰陷阱
    EN_RET_CODE__INTEL_HAS_EXPLORED = 28004,         // 情报探索过了


    EN_RET_CODE__CITY_FIGNTING_CARRY_LORD = 28006,   // 主城正在被打，不能派龙出城
    EN_RET_CODE__EXPLORE_INTEL_EXPEDITION_OUTTIME = 29002,

    EN_RET_CODE__SEARCH_BARBARION_AGE = 29001, // 搜索时代错误

    EN_RET_CODE__REACH_MAX_HOLD_LANDB_UILDING_NUM = 29008, // 想要攻击圣地时，联盟占领的圣地数目已达上限
    EN_RET_CODE__GIVE_UP_LAND_BUILDING_AID_ERROR  = 29009, // 放弃圣地时，圣地已经不属于该联盟
    EN_RET_CODE__RALLY_IS_MARCHING  = 29010, // 集结队伍已经在行军中了

    EN_RET_CODE__CITY_IS_FIGHTING = 29015, //ava进战场时城市正在被攻击
    
    EN_RET_CODE__MERCENARY_PERSONAL_BOSS_CAN_NOT_BE_ATTACKED_NOT_ALLY = 29022, //佣兵荣耀个人怪不可被攻击（不在同一联盟）
    EN_RET_CODE__MERCENARY_PERSONAL_BOSS_CAN_NOT_BE_ATTACKED_CAN_NOT_HELP = 29023, //佣兵荣耀个人怪不可被攻击（未发起帮助）
    EN_RET_CODE__MERCENARY_AL_BOSS_CAN_NOT_BE_ATTACKED_NOT_ALLY = 29024, //佣兵荣耀联盟怪不可被攻击（不在同一联盟）
    EN_RET_CODE__MERCENARY_AL_BOSS_IS_EXISTED = 29025, //佣兵荣耀联盟怪不可被攻击（不在同一联盟）
    EN_RET_CODE__MERCENARY_AL_BOSS_IS_NOT_EXISTED = 29026, //佣兵荣耀联盟怪不存在
    EN_RET_CODE__PICK_TROOP_LEAK                  = 29027, // 队列不够

    EN_RET_CODE__PVP_FULL                         = 29033, // pvp矿区人数已达上限
    EN_RET_CODE__AL_BUILDING_NUM_LIMIT            = 29034, // 联盟建筑数量达到上限
    EN_RET_CODE__PROHIBIT                         = 29035, // 账号封禁

    EN_RET_CODE__BUILDING_QUEUE_LIMIT             = 29041, // 建筑争夺队列数限制
    EN_RET_CODE__NO_DINNER_BUILDING               = 29042, // 没有宴会建筑
    EN_RET_CODE__MOVE_CITY_CHANCELLOR_POS_ERROR   = 29043, // 盟主移城-盟主位置有误
    EN_RET_CODE__CAN_NOT_GEN_LUOHA                = 29058, // 不可生成洛哈
    EN_RET_CODE__CAN_NOT_GEN_MERCERNARY_PERSON_BOSS = 29059, // 不可生成佣兵荣耀怪
    // only server
    EN_RET_CODE__ERROR_COMMAND = 30000,
    EN_RET_CODE__REQ_PARAM_ERROR,               // 请求参数错误
    EN_RET_CODE__ACCOUNT_HAS_USED,
    EN_RET_CODE__ACCOUNT_RELATED,
    EN_RET_CODE__PACKAGE_LEN_OVERFLOW,
    EN_RET_CODE__GET_SESSION_OVERTIME,
    EN_RET_CODE__PARSE_PACKAGE_ERR,
    EN_RET_CODE__TIMEOUT,
    EN_RET_CODE__NO_VALID_DOWNSTEAM,
    EN_RET_CODE__SEND_REQ_FAILED,
    EN_RET_CODE__MYSQL_SQL_CONNECT_FAILED,
    EN_RET_CODE__MYSQL_SQL_SEARCH_FAILED,
    EN_RET_CODE__PROCESS_CMD_ERROR,
    EN_RET_CODE__GET_MAP_FAILED,
    EN_RET_CODE__USER_INFO_INCOMPLETE,
    EN_RET_CODE__DATA_INCOMPLETE,
    EN_RET_CODE__TARGET_NOT_EXIST,
    EN_RET_CODE__TIME_NOT_RIGHT,
    EN_RET_CODE__RESEARCH_DOING,
    EN_RET_CODE__BUILDING_DOING,
    EN_RET_CODE__CANNOT_ATTACT_FRIEND,
    EN_RET_CODE__SEND_RSP_FAILED,
    EN_RET_CODE__OVER_LOAD,     //服务过载

    EN_RET_CODE__BLACKLIST_FULL = 30023,
    EN_RET_CODE__TARGET_LEFT,
    EN_RET_CODE__PLAIN_LACK,
    EN_RET_CODE__BLACK_ACCOUNT,//账号被黑名单命中
    EN_RET_CODE__DATA_CHANGE_FAIL,
    EN_RET_CODE__COMPOSE_DOING = 30028, //合成状态
    EN_RET_CODE__USER_CANNOT_CLEAR_OLD,
    EN_RET_CODE__USER_RECOVER_FAIL,
    EN_RET_CODE__ITEM_NOT_SHOW,
    EN_RET_CODE__GET_IAP_FAIL,
    EN_RET_CODE__REPORT_ID_GET_FAIL,
    EN_RET_CODE__BW_EVENT_PROTECT = 30040,
    EN_RET_CODE__PARSE_EVENT_PACKAGE_ERR,
    EN_RET_CODE__SEND_EVENT_REQ_ERR,
    EN_RET_CODE__NOT_IN_ALLIANCE = 30043,
    EN_RET_CODE__IAP_WHITE_MAX = 30044,
    EN_RET_CODE__AL_COMMENT_IS_FULL = 30045,

    EN_RET_CODE__GET_EVENT_FAIL = 30046,
    EN_RET_CODE__GET_HISTROY_EVENT_FAIL,


    EN_RET_CODE__PARSE_CACHE_PACKAGE_ERR,
    EN_RET_CODE__SEND_CACHE_REQ_ERR,

    EN_RET_CODE__SEND_DATA_CENTER_REQ_ERR,
    EN_RET_CODE__PARSE_DATA_CENTER_PACKAGE_ERR,
    EN_RET_CODE__DATA_CENTER_PACKAGE_FORMAT_ERR,

    EN_RET_CODE__SVR_MERGE_PROTECTED, //合服保护状态
    EN_RET_CODE__SVR_MERGE_TMP,

    EN_RET_CODE__SEND_IAP_SERVER_REQ_ERR,
    EN_RET_CODE__PARSE_IAP_SERVER_PACKAGE_ERR,
    EN_RET_CODE__IAP_SERVER_PACKAGE_FORMAT_ERR,

    EN_RET_CODE__ALREADY_IN_AL_FOR_CREATE_AL = 30060,

    EN_RET_CODE__ACTION_PARAM_NOT_RIGHT,
    EN_RET_CODE__SWEEP_CANT_GEN_OBJ,

    EN_RET_CODE__RESET_CACHE_ERR,

    //新后台新加错误码BEGIN...定义和之前应该存在含义重复...
    EN_RET_CODE__DO_NET_OP_ERROR = 30100, //发送网络请求失败..
    EN_RET_CODE__GET_LOCK_FAILED, //获取锁失败..
    EN_RET_CODE__DOWN_SERVICE_UNAVAILABLE, //下游服务不可用...
    EN_RET_CODE__NET_TYPE_ERROR,
    EN_RET_CODE__DOWN_SERVICE_TIMEOUT,
    EN_RET_CODE__DOWN_SERVICE_PACKAGE_LEN_OVERFLOW,
    EN_RET_CODE__DOWN_SERVICE_PACKAGE_PARSE_ERR,
    EN_RET_CODE__PARSE_REQ_FAIL,
    EN_RET_CODE__SERVICE_TYPE_ERR,
    EN_RET_CODE__SERVICE_SESSION_LACK,
    EN_RET_CODE__SERVICE_NOT_AVAILABLE,
    EN_RET_CODE__GEN_DS_MSG_DATA_FAILED,
    EN_RET_CODE__GET_DS_DATA_KEY_FAILED,
    EN_RET_CODE__PARSE_DS_RSP_FAILED,
    EN_RET_CODE__LUA_CRASH,
    EN_RET_CODE__AL_BUILDING_IS_FIGHTING,
    EN_RET_CODE__USER_IS_NOT_EXIST = 30116,
    //新后台新加错误码END
    
    EN_RET_CODE__ADOBE_SAID_NETWORK_ERROR = 31000,
    EN_RET_CODE__CAN_NOT_FIND_MAP_FOR_RANDOM_MOVE = 31001,

    EN_RET_CODE__NOT_KING,

    EN_RET_CODE__AL_POS_NOT_MATCH = 31003,

    EN_RET_CODE__TRIAL_NOT_INIT = 31004,
    EN_RET_CODE__TRIAL_MODE_NOT_NORMAL,
    EN_RET_CODE__TRIAL_MODE_NOT_RAGE,
    EN_RET_CODE__TRIAL_ATK_TIME_NOT_ENOUGH,
    EN_RET_CODE__TRIAL_NO_GIFT,
    EN_RET_CODE__PURCHASE_CHECK_FAIL,
    EN_RET_CODE__PRO_SYS_GET_DATA_FAIL,
    EN_RET_CODE__ACCOUNT_CHANGE_SVR_FAIL,
    EN_RET_CODE__PURCHASE_CANNOT_CHECK_NEED_RETRY,

    EN_RET_CODE__IAP_SUBSCRIPTION_ERROR = 31100,
    EN_RET_CODE__IAP_SUBSCRIPTION_ERROR_1,
    EN_RET_CODE__IAP_SUBSCRIPTION_ERROR_2,
    EN_RET_CODE__IAP_SUBSCRIPTION_ERROR_3,
    EN_RET_CODE__IAP_SUBSCRIPTION_ERROR_4,
    EN_RET_CODE__IAP_SUBSCRIPTION_ERROR_5,
    EN_RET_CODE__IAP_SUBSCRIPTION_ERROR_6,
    EN_RET_CODE__IAP_SUBSCRIPTION_ERROR_7,
    EN_RET_CODE__IAP_SUBSCRIPTION_ERROR_8,
    EN_RET_CODE__IAP_SUBSCRIPTION_ERROR_9,
    EN_RET_CODE__IAP_SUBSCRIPTION_ERROR_10,
    EN_RET_CODE__IAP_SUBSCRIPTION_ERROR_END = 31200,

    //module@user_linker:32000-32999
    EN_RET_CODE__UL_ERROR_BEGIN = 32000,

    EN_RET_CODE__UL_PARSE_PACKAGE_ERR,
    EN_RET_CODE__UL_GET_UID_ERROR,
    EN_RET_CODE__UL_GET_RES_BUF_ERROR,

    EN_RET_CODE__USM_GET_PUSH_LIST_SIZE_FAIL,
    EN_RET_CODE__USM_GET_PUSH_LIST_FAIL,
    EN_RET_CODE__USM_GET_PUSH_TYPE_ERROR,
    EN_RET_CODE__USM_GET_PUSH_KEY_ERROR,

    EN_RET_CODE__UL_HANDLE_ERROR = 32010,
    EN_RET_CODE__UL_REQ_PACKAGE_HEADER_ERROR = 32011,
    EN_RET_CODE__UL_REQ_PACKAGE_EXTRA_INFO_ERROR = 32012,
    EN_RET_CODE__UL_REQ_PACKAGE_REQUEST_NUM_TOO_BIG = 32013,
    EN_RET_CODE__UL_REQ_USER_LINKER_KEY_ERROR = 32014,

    EN_RET_CODE__UL_ERROR_END = 32999,

    //module@chat:33000-33999
    EN_RET_CODE__CHAT__BEGIN = 33000,
    EN_RET_CODE__CHAT__UPDT_CACHE_ERR,
    EN_RET_CODE__CHAT__FIND_CACHE_ERR,
    EN_RET_CODE__CHAT__BLACK_UID,
    EN_RET_CODE__CHAT__END,

    //module@notic_push_svr:34000-34999
    EN_RET_CODE_NOTIC_PUSH_SVR_BEGIN = 34000,
    EN_RET_CODE_NOTIC_PUSH_SVR_TARGET_UID,
    EN_RET_CODE_NOTIC_PUSH_SVR_TARGET_AID,
    EN_RET_CODE_NOTIC_PUSH_SVR_TARGET_TYPE,  //0 is uid； 1 is aid
    EN_RET_CODE_NOTIC_PUSH_SVR_TARGET_TOKEN,
    EN_RET_CODE_NOTIC_PUSH_SVR_TARGET_PLATFORM,
    EN_RET_CODE_NOTIC_PUSH_SVR_TARGET_SWITCH,
    EN_RET_CODE_NOTIC_PUSH_SVR_TARGET_IDFA,
    EN_RET_CODE_NOTIC_PUSH_SVR_TARGET_LANGUAGE,
    EN_RET_CODE_NOTIC_PUSH_SVR_END,


    EN_RET_CODE__LOCK_GET_ERROR = 35000,
    EN_RET_CODE__LOCK_RELEASE_ERROR,

    EN_RET_CODE__GET_DATA_ERROR,
    EN_RET_CODE__UPDATE_DATA_ERROR,

    EN_RET_CODE__SERVER_IS_MAINTENANCE,
    EN_RET_CODE__USER_DATA_NEED_COMPATIBLE,
    EN_RET_CODE__PERMISSION_DENY,
    EN_RET_CODE__SYNC_CMD_SEQ_ERR,

    EN_RET_CODE__PROVINCE_FULL = 35020, // 省爆满

    //kent@20170907
    //data_d1 err_code
    //procedure@task_process
    EN_RET_CODE__D1__BEGIN = 36000,
    EN_RET_CODE__D1__PREPROCESS_REQ_ERROR,
    EN_RET_CODE__D1__HANDLE_PROCEDURE_ERROR,
    //procedure@cmd_process
    EN_RET_CODE__D1__PROCESS_CMD_BEFORE_ERROR = 36010,
    EN_RET_CODE__D1__PROCESS_CMD_ERROR,
    EN_RET_CODE__D1__GET_DATA_ERROR,
    EN_RET_CODE__D1__UPDATE_DB_ERROR,

    EN_RET_CODE__D1__REQ_UNPACK_ERROR = 36020,
    EN_RET_CODE__D1__SERVER_HAS_STOP,
    EN_RET_CODE__D1__GET_VIRTUAL_NODE_FAIL,
    EN_RET_CODE__D1__ANALYZE_CMD_TABLE_INFO_ERROR,
    EN_RET_CODE__D1__CHECK_REQ_DB_DATA_ERROR,
    EN_RET_CODE__D1__NO_VALID_DOWN_REQ,
    EN_RET_CODE__D1__DOWN_REQ_NUM_OVER_THRESHHOLD,
    EN_RET_CODE__D1__GET_DOWN_NODE_ERROR,
    EN_RET_CODE__D1__SEND_TASK_GROUP_ERROR,
    EN_RET_CODE__D1__PARSE_RSP_JSON_ERROR,
    EN_RET_CODE__D1__ON_DATA_RSP_ERROR,
    EN_RET_CODE__D1__OVER_LOAD,
    EN_RET_CODE__D1__PUSH_DELAY_REQ_FAIL,
    EN_RET_CODE__D1__SEARCH_IO_TIMEOUT,
    EN_RET_CODE__D1__RSP_PACKAGE_LEN_OVERFLOW,
    EN_RET_CODE__D1__PARSE_RSP_PACKAGE_ERROR,
    EN_RET_CODE__D1__DOWN_NODE_RET_CODE_ERROR,
    EN_RET_CODE__D1__SEND_RSP_FAILED,

    EN_RET_CODE__D1__END = 36999,

    //jesse@20180416
    //data_d2 err_code
    EN_RET_CODE__D2__BEGIN = 37000,
    EN_RET_CODE__D2__SERVICE_TYPE_ERROR,
    EN_RET_CODE__D2__PARAM_ERROR,
    EN_RET_CODE__D2__PROCESS_ERROR,
    EN_RET_CODE__D2__REDIS_WRITE_FAIL,
    EN_RET_CODE__D2__REDIS_REQ_SEND_FAIL,
    EN_RET_CODE__D2__DYNAMODB_READ_ERROR,
    EN_RET_CODE__D2__DYNAMODB_REQ_SEND_ERROR,
    EN_RET_CODE__D2__DYNAMODB_CONNECTER_ERROR,
    EN_RET_CODE__D2__DISK_QUEUE_ERROR,
    EN_RET_CODE__D2__SENTINEL_ABNORMAL,
    EN_RET_CODE__D2__SENTINEL_CONNECTION_ERROR,
    EN_RET_CODE__D2__SENTINEL_REQ_SEND_FAIL,
    EN_RET_CODE__D2__SENTINEL_READ_ERROR,
    EN_RET_CODE__D2__REDIS_FLUSH_FAIL,
    EN_RET_CODE__D2__END = 37099,

    //iap err_code : no need retry
    EN_RET_CODE__IAP_NO_RETRY__BEGIN = 37100,
    EN_RET_CODE__IAP_NO_RETRY__REQ_PARAM_ERROR = 37101,
    EN_RET_CODE__IAP_NO_RETRY__WHITE_MAX = 37102,
    EN_RET_CODE__IAP_NO_RETRY__PURCHASE_CHECK_FAIL = 37103,
    EN_RET_CODE__IAP_NO_RETRY__NOT_IN_WHITE_LIST_BUT_USE_SANDBOX = 37104, 
    EN_RET_CODE__IAP_NO_RETRY__RE_GEM_RECHARGE = 37105,
    EN_RET_CODE__IAP_NO_RETRY__HACKER = 37106,

    // iap web store code
    EN_RET_CODE__WEB_IAP_INVALID_PARAM = 37107,         // 参数错误
    EN_RET_CODE__WEB_IAP_INVALID_USER = 37108,          // uid错误
    EN_RET_CODE__WEB_IAP_INVALID_SKU = 37109,           // sku不在配置中
    EN_RET_CODE__WEB_IAP_SKU_PRICE_INVALID = 37110,     // 购买价格与配置不符
    EN_RET_CODE__WEB_IAP_TRANS_ID_INVALID = 37111,      // trans_id 错误
    EN_RET_CODE__WEB_IAP_REASON_CAN_NOT_REFUND = 37112, // 退款原因不能自动退款
    EN_RET_CODE__WEB_IAP_COUPON_USED = 37113,           // 折扣券已经使用过
    EN_RET_CODE__WEB_IAP_ORDER_ALREADY_REFUND = 37114,  // 订单已经退款
    EN_RET_CODE__WEB_IAP_ACCESS_TOKEN_INVALID = 37115,  // access_token不对

    EN_RET_CODE__IAP_IAP_USE_ILLEGAL = 37198,

    EN_RET_CODE__IAP_NO_RETRY__END = 37199,
    //iap err_code : manual handle
    EN_RET_CODE__IAP_MANUAL__BEGIN = 37200,
    EN_RET_CODE__IAP_MANUAL__ADD_REWAED_FAIL = 37201,
    EN_RET_CODE__IAP_MANUAL__PLATFORM_CHANGE = 37202,
    EN_RET_CODE__IAP_MANUAL__PLATFORM_ACCOUNT_CHANGE = 37203,
    EN_RET_CODE__IAP_MANUAL__ACCOUNT_NOT_MATCH = 37204,
    EN_RET_CODE__IAP_MANUAL__PURCHASE_NOT_MATCH = 37205,
    EN_RET_CODE__IAP_MANUAL__SUBSCRIPTION_ERROR = 37206,
    EN_RET_CODE__IAP_MANUAL__END = 37299,

    // purchase_check
    EN_RET_CODE__CHECK_PURCHASE_TOKEN_ERROR,
    EN_RET_CODE__REFRESH_TOKEN_ERROR,

    EN_RET_CODE__SERVER_HAS_STOP,

    // map_center
    EN_RET_CODE__POS_NOT_AVAILABLE,

    EN_RET_CODE__SUNSETCANYON_TARGET_INFO_CHANGE = 37305,
    EN_RET_CODE__LVL_BATTLE_SVR_USER_LIMIT  = 37311,

    EN_RET_CODE_PURCHASE_CHECK_FAIL_PENDING = 37600,

    EN_RET_CODE__ACCOUNT_DELETE_APPLY_RECHARGE_ERROR = 40022,

    // 38101 - 38199 为 web删除账号 使用的错误码
    EB_RET_CODE__WEB_DECLACC_BEGIN = 38101,
    EB_RET_CODE__CHECK_SEED_FAILED = 38101,
    EB_RET_CODE__CHECK_COND_FAILED = 38102,
    EB_RET_CODE__ACCOUNT_DELING    = 38103,
    EB_RET_CODE__WEB_DECLACC_END   = 38199,

    //login_center error
    EN_RET_CODE__LOGIN_CENTER_ACCOUNT_DELETE_APPLY_FAIL = 40021, // "验证失败，无法确认是否为账号拥有者。"
    EN_RET_CODE__LOGIN_CENTER_ACCOUNT_DELETE_FREEZE_FAIL = 40023, // "申请失败，请确认已达成下列条件："
    EN_RET_CODE__LOGIN_CENTER_ERROR_BEGIN = 41000,

    EN_RET_CODE__LOGIN_CENTER_PARAM_ERROR = 41002,
    EN_RET_CODE__LOGIN_CENTER_SEND_FAIL = 41003,

    EN_RET_CODE__LOGIN_CENTER_PACKAGE_LEN_OVERFLOW = 41005,
    EN_RET_CODE__LOGIN_CENTER_PARSE_AWS_PACKAGE_ERR = 41006,
    EN_RET_CODE__LOGIN_CENTER_PARSE_HU_PACKAGE_ERR = 41007,

    EN_RET_CODE__LOGIN_CENTER_GET_LOCK_FAIL = 41011,

    EN_RET_CODE__LOGIN_CENTER_STATUS_ERROR = 42001,
    EN_RET_CODE__LOGIN_CENTER_PASSWORD_CHANGE = 42004,

    EN_RET_CODE__LOGIN_CENTER_BLACK_ACCOUNT = 42005,
    EN_RET_CODE__LOGIN_CENTER_ACCOUNT_INFO_INVALID = 42006,
    EN_RET_CODE__LOGIN_CENTER_ACCOUNT_NOT_GAME_DATA = 42007,
    EN_RET_CODE__LOGIN_CENTER_AMULTI_EMAIL = 42008,
    EN_RET_CODE__LOGIN_CENTER_EMAIL_HAS_MULTI_GAME_DATA = 42009,
    EN_RET_CODE__LOGIN_CENTER_PRODUCTION_INFO_INVALID = 42010,
    EN_RET_CODE__LOGIN_CENTER_USER_DATA_NOT_EXIST = 42011,

    EN_RET_CODE__LOGIN_CENTER_ERROR_SID = 42020,
    EN_RET_CODE__LOGIN_CENTER_ERROR_UID = 42021,
    EN_RET_CODE__LOGIN_CENTER_FATAL_ERROR = 42022,
    EN_RET_CODE__LOGIN_CENTER_STATICFILE_ERROR = 42023,

    EN_RET_CODE__LOGIN_CENTER_PRODUCT_LIMIT = 42030,
    EN_RET_CODE__LOGIN_CENTER_PLAYER_INFO_INVALID = 42031,
    EN_RET_CODE__LOGIN_CENTER_SIGN_OFF_INFO_INVALID = 42032,

    EN_RET_CODE__LOGIN_CENTER_LOGIN_IN_OTHER_DEVICE = 42033,
    EN_RET_CODE__LOGIN_CENTER_PARSE_ACCOUNT_PKG_FAIL = 42034,

    EN_RET_CODE__LOGIN_CENTER_ERROR_END = 42999,

    EN_RET_CODE__LOGIN_CENTER_IP_NULL = 43000,

    // account_product_svr 错误码
    EN_RET_CODE__ACCOUNT_PRODUCT_ACCOUNT_ALREADY_BIND = 44000, //外部账号已经绑定uid了，需要先解绑
    EN_RET_CODE__ACCOUNT_PRODUCT_ACCOUNT_NOT_EXIST = 44001, //外部账号不存在
    EN_RET_CODE__ACCOUNT_PRODUCT_UID_NOT_EXIST = 44002, //请求的uid无效
    EN_RET_CODE__ACCOUNT_PRODUCT_UID_NOT_MAIN = 44003,  //绑定的uid不是主账号
    EN_RET_CODE__ACCOUNT_PRODUCT_UID_ALREADY_EXIST = 44004, //创建新号绑定的uid已经存在了

    //返回50000-60000的错误码时, 客户端会reload
    EN_RET_CODE__NEED_RELOAD_BEGIN = 50000,

    EN_RET_CODE__SID_ERROR,
    EN_RET_CODE__DEAD_PLAYER_NOT_LOGIN,
    EN_RET_CODE__PLAYER_NEED_MERGET_TO_ANOTHER_SVR,

    EN_RET_CODE__GS_VERSION_INVALID = 50005,
    EN_RET_CODE__AVA_VERSION_INVALID = 50006,
    EN_RET_CODE__LVL_VERSION_INVALID = 50007,

    EN_RET_CODE__NEED_RELOAD_END = 60000,

    // 100000以后也是业务错误码
    EN_RET_CODE__MERCENARY_PERSONAL_BOSS_IN_RALLY = 100004,   // 个人boss怪正在被rally，不能修改求助
    EN_RET_CODE__MERCENARY_CAR_NOT_EXIST = 100007,   // 车不在了 过期了
    EN_RET_CODE__USER_NOT_IN_GS = 100011,    // 玩家不在本服地图上
    EN_RET_CODE__ATTACK_ALLY = 100012,  // 掠夺盟友
    EN_RET_CODE__CITY_NOT_IN_GS = 100015,  // 城市不在地图上
    EN_RET_CODE__KINGDOM_TITLE_APPLY_FULL = 100039, // 官职申请队列已满
    EN_RET_CODE__KINGDOM_TITLE_RESERVATION_FULL = 100040, // 官职预约队列已满

    EN_RET_CODE__CAST_PLAYER_NOT_KINGDOM = 100041, // 不是国王
    EN_RET_CODE__PLAYER_NOT_IN_MAP = 100042, // 不能使用该技能
    EN_RET_CODE__TARGET_CASTLE_LV_TO_LOW = 100043, // 主城等级不够
    EN_RET_CODE__LVL_NO_ENEMY_BUILDING = 100047,    // ava敌方没有占领的建筑
    
    EN_RET_CODE__CHAT_INVITE_ALREADY_EXIST = 100048, // 好友申请已经存在

    EN_RET_CODE__NO_BIND_EMAIL = 100050, // 没有绑定账号无法注销

    EN_RET_CODE__PLAYER_NOT_IN_SVR = 100051, // 挑战目标已不在服务器
    EN_RET_CODE__PVP_ATTACK_LIMIT = 100060, // 处于停火状态，无法发起攻击
};

enum EMonitorNetRetcode
{
    EN_RET_CODE_MONITOR_HTTP_NET_TIME_OUT     = 1000,
    EN_RET_CODE_MONITOR_HTTP_NET_CONNECT_FAIL = 1001,
};

#endif
